tinyMCE.addI18n({es:{
common:{
edit_confirm:" \u00BFDesea utilizar el modo WYSIWYG para esta caja de texto?",
apply:"Aplicar",
insert:"Insertar",
update:"Actualizar",
cancel:"Cancelar",
close:"Cerrar",
browse:"Examinar",
class_name:"Clase",
not_set:"-- Ninguno --",
clipboard_msg:"Copiar/Cortar/Pegar no se encuentra disponible en Mozilla y Firefox.\n \u00BFDesea obtener m\u00E1s informaci\u00F3n acerca de este tema?",
clipboard_no_support:"Su navegador no soporta las funciones de cortapapeles, use los accesos por teclado.",
popup_blocked:"Lo sentimos, su bloqueo de ventanas emergentes ha deshabilitado una ventana que provee funcionalidades a la aplicaci\u00F3n. Necesita deshabilitar este bloqueo en este sitio para poder utilizar todas las funciones.",
invalid_data:"Error: Introdujo un valor no v\u00E1lido, est\u00E1n marcados en rojo.",
more_colors:"M\u00E1s colores"
},
contextmenu:{
align:"Alineaci\u00F3n",
left:"Izquierda",
center:"Centrado",
right:"Derecha",
full:"Justificado"
},
insertdatetime:{
date_fmt:"%d-%m-%Y",
time_fmt:"%H:%M:%S",
insertdate_desc:"Insertar fecha",
inserttime_desc:"Insertar hora",
months_long:"Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre",
months_short:"Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic",
day_long:"Domingo,Lunes,Martes,Mi\u00E9rcoles,Jueves,Viernes,S\u00E1bado,Domingo",
day_short:"Dom,Lun,Mar,Mie,Jue,Vie,Sab,Dom"
},
print:{
print_desc:"Imprimir"
},
preview:{
preview_desc:"Vista previa"
},
directionality:{
ltr_desc:"Direcci\u00F3n izquierda a derecha",
rtl_desc:"Direcci\u00F3n derecha a izquierda"
},
layer:{
insertlayer_desc:"Insertar nueva capa",
forward_desc:"Avanzar",
backward_desc:"Retroceder",
absolute_desc:"Cambiar a posici\u00F3n absoluta",
content:"Nueva capa..."
},
save:{
save_desc:"Guardar",
cancel_desc:"Cancelar todos los cambios"
},
nonbreaking:{
nonbreaking_desc:"Insertar caracter de espacio 'non-breaking'"
},
iespell:{
iespell_desc:"Corrector ortogr\u00E1fico",
download:"No se detect\u00F3 'ieSpell'.  \u00BFDesea instalarlo ahora?"
},
advhr:{
advhr_desc:"Regla horizontal"
},
emotions:{
emotions_desc:"Emoticones"
},
searchreplace:{
search_desc:"Buscar",
replace_desc:"Buscar/Reemplazar"
},
advimage:{
image_desc:"Insertar/editar imagen"
},
advlink:{
link_desc:"Insertar/editar hiperv\u00EDnculo"
},
xhtmlxtras:{
cite_desc:"Cita",
abbr_desc:"Abreviatura",
acronym_desc:"Acr\u00F3nimo",
del_desc:"Borrado",
ins_desc:"Inserci\u00F3n",
attribs_desc:"Insertar/Editar atributos"
},
style:{
desc:"Editar Estilo CSS"
},
paste:{
paste_text_desc:"Pegar como texto plano",
paste_word_desc:"Pegar desde Word",
selectall_desc:"Elegir todo",
plaintext_mode_sticky:"Paste is now in plain text mode. Click again to toggle back to regular paste mode. After you paste something you will be returned to regular paste mode.",
plaintext_mode:"Paste is now in plain text mode. Click again to toggle back to regular paste mode."
},
paste_dlg:{
text_title:"Use CTRL+V en su teclado para pegar el texto en la ventana.",
text_linebreaks:"Keep linebreaks",
word_title:"Use CTRL+V en su teclado para pegar el texto en la ventana."
},
table:{
desc:"Inserta una nueva tabla",
row_before_desc:"Insertar fila (antes)",
row_after_desc:"Insertar fila (despu\u00E9s)",
delete_row_desc:"Suprimir fila",
col_before_desc:"Insertar columna (antes)",
col_after_desc:"Insertar columna (despu\u00E9s)",
delete_col_desc:"Suprimir columna",
split_cells_desc:"Dividir celdas",
merge_cells_desc:"Vincular celdas",
row_desc:"Propiedades de la fila",
cell_desc:"Propiedades de la celda",
props_desc:"Propiedades de la tabla",
paste_row_before_desc:"Pegar filas (antes)",
paste_row_after_desc:"Pegar filas (despu\u00E9s)",
cut_row_desc:"Cortar fila",
copy_row_desc:"Copiar fila",
del:"Eliminar tabla",
row:"Fila",
col:"Columna",
cell:"Celda"
},
autosave:{
unload_msg:"Los cambios realizados se perder\u00E1n si sale de esta p\u00E1gina.",
restore_content:"Reestablecer contenido guardado autom\u00E1ticamente",
warning_message:"Se reestablece en contenido guardado, perder\u00E1 todo el contenido que est\u00E1 actualmente en el editor.\n\nEst\u00E1 seguro de que quiere reestablecer el contenido guardado."
},
fullscreen:{
desc:"Cambiar a modo Pantalla Completa"
},
media:{
desc:"Insertar/editar medio embebido",
edit:"Editar medio embebido"
},
fullpage:{
desc:"Propiedades del documento",
delta_width:"Ancho",
delta_height:"Alto"
},
template:{
desc:"Insertar contenido de plantilla predefinida"
},
visualchars:{
desc:"Caracteres de control ON/OFF."
},
spellchecker:{
desc:"Cambiar a corrector ortogr\u00E1fico",
menu:"Configuraci\u00F3n de corrector ortogr\u00E1fico",
ignore_word:"Ignorar",
ignore_words:"Ignorar todo",
langs:"Idiomas",
wait:"Espere...",
sug:"Sugerencias",
no_sug:"Sin sugerencias",
no_mpell:"No se encontraron errores."
},
pagebreak:{
desc:"Insertar fin de p\u00E1gina"
},
advlist:{
types:"Tipo",
def:"Preestablecido",
lower_alpha:"Menos opaco",
lower_greek:"Menos greek",
lower_roman:"Menos roman",
upper_alpha:"M\u00E1s opaco",
upper_roman:"M\u00E1s roman",
circle:"Circulo",
disc:"Disc",
square:"Cuadro"
}}});
tinyMCE.addI18n('es.advanced',{
style_select:"Estilos",
font_size:"Tama\u00F1o",
fontdefault:"Fuente",
block:"Formato",
paragraph:"P\u00E1rrafo",
div:"Div",
address:"Direcci\u00F3n",
pre:"Preformateado",
h1:"Encabezado 1",
h2:"Encabezado 2",
h3:"Encabezado 3",
h4:"Encabezado 4",
h5:"Encabezado 5",
h6:"Encabezado 6",
blockquote:"Cita",
code:"C\u00F3digo",
samp:"Ejemplo de c\u00F3digo",
dt:"T\u00E9rmino de definici\u00F3n",
dd:"Descripci\u00F3n de definici\u00F3n",
bold_desc:"Negrita (Ctrl+B)",
italic_desc:"Cursiva (Ctrl+I)",
underline_desc:"Subrayado (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Alinear a la izquierda",
justifycenter_desc:"Alinear al centro",
justifyright_desc:"Alinear a la derecha",
justifyfull_desc:"Justificar",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Reducir sangr\u00EDa",
indent_desc:"Aumentar sangr\u00EDa",
undo_desc:"Deshacer (Ctrl+Z)",
redo_desc:"Rehacer (Ctrl+Y)",
link_desc:"Insertar/editar hiperv\u00EDnculo",
unlink_desc:"Quitar hiperv\u00EDnculo",
image_desc:"Insertar/editar imagen",
cleanup_desc:"Limpiar c\u00F3digo basura",
code_desc:"Editar c\u00F3digo HTML",
sub_desc:"Sub\u00EDndice",
sup_desc:"Super\u00EDndice",
hr_desc:"Insertar regla horizontal",
removeformat_desc:"Limpiar formato",
custom1_desc:"Su descripci\u00F3n personal aqu\u00ED",
forecolor_desc:"Elegir color del texto",
backcolor_desc:"Elegir color de fondo",
charmap_desc:"Insertar caracteres personalizados",
visualaid_desc:"Mostrar/ocultar l\u00EDnea de gu\u00EDa/elementos invisibles",
anchor_desc:"Insertar/editar ancla",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Pegar",
image_props_desc:"Propiedades de imagen",
newdocument_desc:"Nuevo documento",
help_desc:"Ayuda",
blockquote_desc:"Cita",
clipboard_msg:"Copiar/Cortar/Pegar no se encuentra disponible en Mozilla y Firefox.\n \u00BFQuiere m\u00E1s informaci\u00F3n sobre este tema?",
path:"Ruta",
newdocument:" \u00BFSeguro que desea limpiar todo el contenido?",
toolbar_focus:"Ir a los botones de herramientas - Alt+Q, Ir al editor - Alt-Z, Ir a la ruta del elemento - Alt-X",
more_colors:"M\u00E1s colores"
});
tinyMCE.addI18n('es.advanced_dlg',{
about_title:"Acerca de TinyMCE",
about_general:"Acerca de ",
about_help:"Ayuda",
about_license:"Licencia",
about_plugins:"Complementos",
about_plugin:"Complemento",
about_author:"Autor",
about_version:"Versi\u00F3n",
about_loaded:"Complementos cargados",
anchor_title:"Insertar/editar ancla",
anchor_name:"Nombre del ancla",
code_title:"Editor del c\u00F3digo fuente HTML",
code_wordwrap:"Ajustar al margen",
colorpicker_title:"Elegir color",
colorpicker_picker_tab:"Selector",
colorpicker_picker_title:"Paleta de color",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta de colores",
colorpicker_named_tab:"Nombrados",
colorpicker_named_title:"Colores nombrados",
colorpicker_color:"Color:",
colorpicker_name:"Nombre:",
charmap_title:"Elegir caracter personalizado",
image_title:"Insertar/editar imagen",
image_src:"URL de la Imagen",
image_alt:"Descripci\u00F3n de la Imagen",
image_list:"Lista de la Imagen",
image_border:"Borde",
image_dimensions:"Dimensi\u00F3n",
image_vspace:"Espacio vertical",
image_hspace:"Espacio horizontal",
image_align:"Alineaci\u00F3n",
image_align_baseline:"L\u00EDnea base",
image_align_top:"Arriba",
image_align_middle:"Medio",
image_align_bottom:"Debajo",
image_align_texttop:"Texto arriba",
image_align_textbottom:"Texto debajo",
image_align_left:"Izquierda",
image_align_right:"Derecha",
link_title:"Insertar/editar hiperv\u00EDnculo",
link_url:"URL del hiperv\u00EDnculo",
link_target:"Destino",
link_target_same:"Abrir v\u00EDnculo en la misma ventana",
link_target_blank:"Abrir v\u00EDnculo en una ventana nueva",
link_titlefield:"T\u00EDtulo",
link_is_email:"La URL que introdujo parece ser una direcci\u00F3n de email,  \u00BFdesea agregar el prefijo mailto: necesario?",
link_is_external:"La URL que introdujo parece ser un v\u00EDnculo externo,  \u00BFdesea agregar el prefijo http:// necesario?",
link_list:"Lista de hiperv\u00EDnculos"
});
tinyMCE.addI18n('es.advimage_dlg',{
tab_general:"General",
tab_appearance:"Apariencia",
tab_advanced:"Avanzado",
general:"General",
title:"T\u00EDtulo",
preview:"Vista previa",
constrain_proportions:"Bloquear relaci\u00F3n de aspecto",
langdir:"Direcci\u00F3n del lenguaje",
langcode:"C\u00F3digo del lenguaje",
long_desc:"V\u00EDnculo para descripci\u00F3n larga",
style:"Estilos",
classes:"Clases",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
id:"Id",
map:"Mapa de imagen",
swap_image:"Intercambiar imagen",
alt_image:"Imagen alternativa",
mouseover:"para mouseover",
mouseout:"para mouseout",
misc:"Miscel\u00E1neo",
example_img:"Vista previa de la imagen",
missing_alt:" \u00BFEsta seguro de continuar sin introducir una descripci\u00F3n a la imagen? Sin ella puede no ser accesible para usuarios con discapacidades, o para aquellos que usen navegadores de modo texto, o tengan deshabilitadas las im\u00E1genes de la p\u00E1gina.",
dialog_title:"Insertar/editar imagen",
src:"URL de la imagen",
alt:"Descripci\u00F3n de la imagen",
list:"Lista de imagen",
border:"Bordes",
dimensions:"Dimensiones",
vspace:"Espacio vertical",
hspace:"Espacio horizontal",
align:"Alineaci\u00F3n",
align_baseline:"L\u00EDnea base",
align_top:"Arriba",
align_middle:"Medio",
align_bottom:"Debajo",
align_texttop:"Texto arriba",
align_textbottom:"Texto abajo",
align_left:"Izquierda",
align_right:"Derecha",
image_list:"Lista de imagen"
});
tinyMCE.addI18n('es.advlink_dlg',{
title:"Insertar/editar hiperv\u00EDnculo",
url:"URL del hiperv\u00EDnculo",
target:"Destino",
titlefield:"T\u00EDtulo",
is_email:"La URL que ha introducido parece ser una direci\u00F3n de correo,  \u00BFdesea agregar el prefijo mailto: necesario?",
is_external:"La URL que ha introducido parece ser un v\u00EDnculo externo,  \u00BFdesea agregar el prefijo http:// necesario?",
list:"Lista de v\u00EDnculos",
general_tab:"General",
popup_tab:"Ventana emergente",
events_tab:"Eventos",
advanced_tab:"Avanzado",
general_props:"Propiedades generales",
popup_props:"Propiedades de ventanas emergentes",
event_props:"Eventos",
advanced_props:"Propiedades avanzadas",
popup_opts:"Opciones",
anchor_names:"Anclas",
target_same:"Abrir en esta ventana / marco",
target_parent:"Abrir en ventana padre / marco",
target_top:"Abrir en el marco superior (reemplaza todos los marcos)",
target_blank:"Abrir en ventana nueva",
popup:"Javascript popup",
popup_url:"URL de la ventana emergente",
popup_name:"Nombre de la ventana",
popup_return:"Insertar 'return false'",
popup_scrollbars:"Barras de desplazamiento",
popup_statusbar:"Barra de estado",
popup_toolbar:"Barra de herramientas",
popup_menubar:"Barra de men\u00FA",
popup_location:"Barra de localizaci\u00F3n",
popup_resizable:"Permitir cambiar el tama\u00F1o de la ventana",
popup_dependent:"Dependientes (s\u00F3lo Mozilla/Firefox)",
popup_size:"Tama\u00F1o",
popup_position:"Posici\u00F3n (X/Y)",
id:"Id",
style:"Estilo",
classes:"Clases",
target_name:"Nombre del Target",
langdir:"Direcci\u00F3n del lenguaje",
target_langcode:"Lenguaje del Target",
langcode:"C\u00F3digo del lenguaje",
encoding:"Codificaci\u00F3n de caracteres del Target",
mime:"Tipo MIME del Target",
rel:"Relaci\u00F3n p\u00E1gina a target",
rev:"Relaci\u00F3n target a p\u00E1gina",
tabindex:"Indice de tabulaci\u00F3n",
accesskey:"Tecla de acceso",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
link_list:"Lista de v\u00EDnculo"
});
tinyMCE.addI18n('es.emotions_dlg',{
title:"Insertar emoticon",
desc:"Emoticones",
cool:"Todo bien",
cry:"Llora",
embarassed:"Verg\u00FCenza",
foot_in_mouth:"Pie en la boca",
frown:"Triste",
innocent:"Inocente",
kiss:"Beso",
laughing:"Risa",
money_mouth:"Dinero boca",
sealed:"Sellado",
smile:"Sonrisa",
surprised:"Sorprendido",
tongue_out:"Lengua fuera",
undecided:"Indeciso",
wink:"Gui\u00F1o",
yell:"Enfadado"
});
tinyMCE.addI18n('es.media_dlg',{
title:"Insertar/editar medio embebido",
general:"General",
advanced:"Avanzado",
file:"Archivo/URL",
list:"Lista",
size:"Dimensiones",
preview:"Vista Previa",
constrain_proportions:"Bloquear relaci\u00F3n de aspecto",
type:"Tipo",
id:"Id",
name:"Nombre",
class_name:"Clase",
vspace:"V-Space",
hspace:"H-Space",
play:"Comienzo Autom\u00E1tico",
loop:"Repetitivo",
menu:"Mostrar Men\u00FA",
quality:"Calidad",
scale:"Scale",
align:"Alineaci\u00F3n",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fondo",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cach\u00E9",
hidden:"Hidden",
controller:"Controller",
kioskmode:"Kiosk mode",
playeveryframe:"Reproducir todo los frames",
targetcache:"Target cache",
correction:"Sin correci\u00F3n",
enablejavascript:"Habilitar JavaScript",
starttime:"Inicio",
endtime:"Fin",
href:"Href",
qtsrcchokespeed:"Vel. de choque",
target:"Target",
volume:"Volumen",
autostart:"Comienzo Autom\u00E1tico",
enabled:"Habilitado",
fullscreen:"Pantalla Completa",
invokeurls:"Invocar URLs",
mute:"Silencio",
stretchtofit:"Estirar para ajustar",
windowlessvideo:"Video sin ventana",
balance:"Balance",
baseurl:"URL Base",
captioningid:"Captioning id",
currentmarker:"Marcador actual",
currentposition:"Posici\u00F3n actual",
defaultframe:"Frame predet.",
playcount:"Cuantas reproducciones",
rate:"Ratio",
uimode:"Modo UI",
flash_options:"Opciones Flash",
qt_options:"Opciones Quicktime",
wmp_options:"Opciones Windows media player",
rmp_options:"Opciones Real media player",
shockwave_options:"Opciones Shockwave",
autogotourl:"Ir a URL autom\u00E1t.",
center:"Centrado",
imagestatus:"Estado de imagen",
maintainaspect:"Mantener aspecto",
nojava:"No java",
prefetch:"Preb\u00FAsqueda",
shuffle:"Aleatorio",
console:"Consola",
numloop:"N\u00FAm. repeticiones",
controls:"Controles",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Estilo estiramiento",
swstretchhalign:"Alin. H. Estiramiento",
swstretchvalign:"Alin. V. Estiramiento",
sound:"Sonido",
progress:"Progreso",
qtsrc:"QT Src",
qt_stream_warn:"Los recursos rtsp de Streaming deber\u00EDan a\u00F1adirse en el campo QT Src de la pesta\u00F1a avanzada.\nAdem\u00E1s deber\u00EDa a\u00F1adir una versi\u00F3n no Streaming en el campo Src.",
align_top:"Arriba",
align_right:"Derecha",
align_bottom:"Debajo",
align_left:"Izquierda",
align_center:"Centrado",
align_top_left:"Arriba Izda.",
align_top_right:"Arriba Dcha.",
align_bottom_left:"Debajo Izda.",
align_bottom_right:"Debajo Dcha.",
flv_options:"Opciones Video Flash",
flv_scalemode:"Modo escalado",
flv_buffer:"Buffer",
flv_startimage:"Imagen inicio",
flv_starttime:"Tiempo inicio",
flv_defaultvolume:"Volumen predet.",
flv_hiddengui:"Ocultar GUI",
flv_autostart:"Inicio auto.",
flv_loop:"Repetitivo",
flv_showscalemodes:"Mostrar modos escala",
flv_smoothvideo:"Video suave",
flv_jscallback:"JS Callback"
});
tinyMCE.addI18n('es.paste_dlg',{
text_title:"Use CTRL+V en su teclado para pegar el texto en la ventana.",
text_linebreaks:"Keep linebreaks",
word_title:"Use CTRL+V en su teclado para pegar el texto en la ventana."
});
tinyMCE.addI18n('es.searchreplace_dlg',{
searchnext_desc:"Buscar de nuevo",
notfound:"La b\u00FAsqueda se ha completado. No se encontr\u00F3 el texto introducido.",
search_title:"Buscar",
replace_title:"Buscar/Reemplazar",
allreplaced:"Se ha reemplazado el texto.",
findwhat:"Qu\u00E9 buscar",
replacewith:"Reemplazar por",
direction:"Direcci\u00F3n",
up:"Arriba",
down:"Abajo",
mcase:"Min\u00FAs./May\u00FAs.",
findnext:"Buscar siguiente",
replace:"Reemplazar",
replaceall:"Reemplazar todo"
});
tinyMCE.addI18n('es.style_dlg',{
title:"Editar Estilo CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fondo",
block_tab:"Bloque",
box_tab:"Caja",
border_tab:"Borde",
list_tab:"Lista",
positioning_tab:"Posici\u00F3n",
text_props:"Texto",
text_font:"Fuente",
text_size:"Tama\u00F1o",
text_weight:"Peso",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Ancho de la fila",
text_case:"Min\u00FAs./May\u00FAs.",
text_color:"Color",
text_decoration:"Decorativos",
text_overline:"Subrayado superior",
text_underline:"Subrayado",
text_striketrough:"Tachado",
text_blink:"Parpadeo",
text_none:"Ninguno",
background_color:"Color de fondo",
background_image:"Imagen de fondo",
background_repeat:"Repetici\u00F3n",
background_attachment:"Adjunto",
background_hpos:"Posici\u00F3n horizontal",
background_vpos:"Posici\u00F3n vertical",
block_wordspacing:"Espacio entre palabra",
block_letterspacing:"Espacio entre letra",
block_vertical_alignment:"Alineaci\u00F3n vertical",
block_text_align:"Alineaci\u00F3n del texto",
block_text_indent:"Sangr\u00EDa",
block_whitespace:"Espacio en blanco",
block_display:"Display",
box_width:"Ancho",
box_height:"Alto",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Lo mismo en todos",
top:"Arriba",
right:"Derecha",
bottom:"Debajo",
left:"Izquierda",
margin:"Margen",
style:"Estilo",
width:"Ancho",
height:"Alto",
color:"Color",
list_type:"Tipo",
bullet_image:"Imagen de la vi\u00F1eta",
position:"Posici\u00F3n",
positioning_type:"Tipo",
visibility:"Visibilidad",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});