tinyMCE.addI18n({fi:{
common:{
edit_confirm:"Haluatko k\u00E4ytt\u00E4\u00E4 WYSIWYG tilaa t\u00E4ss\u00E4 tekstikent\u00E4ss\u00E4?",
apply:"K\u00E4yt\u00E4",
insert:"Lis\u00E4\u00E4",
update:"P\u00E4ivit\u00E4",
cancel:"Peruuta",
close:"Sulje",
browse:"Selaa",
class_name:"Luokka",
not_set:"-- Ei m\u00E4\u00E4ritetty --",
clipboard_msg:"Kopioi/Leikkaa/Liit\u00E4 ei ole k\u00E4ytett\u00E4viss\u00E4 Mozilla ja Firefox selaimilla.\nHaluatko lis\u00E4tietoa t\u00E4st\u00E4 ongelmasta?",
clipboard_no_support:"Selaimesi ei ole tuettu, k\u00E4yt\u00E4 sen sijaan n\u00E4pp\u00E4in oikoteit\u00E4.",
popup_blocked:"Sinulla on k\u00E4yt\u00F6ss\u00E4si ohjelma, joka est\u00E4\u00E4 ponnahdusikkunoiden n\u00E4yt\u00F6n. Sinun t\u00E4ytyy kytke\u00E4 ponnahdusikkunoiden esto pois p\u00E4\u00E4lt\u00E4 voidaksesi hy\u00F6dynt\u00E4\u00E4 t\u00E4ysin t\u00E4t\u00E4 ty\u00F6kalua.",
invalid_data:"Virhe: Sy\u00F6tit virheellisi\u00E4 arvoja, ne n\u00E4kyv\u00E4t punaisina.",
more_colors:"Enemm\u00E4n v\u00E4rej\u00E4"
},
contextmenu:{
align:"Tasaus",
left:"Vasemmalle",
center:"Keskelle",
right:"Oikealle",
full:"Molemmille puolille"
},
insertdatetime:{
date_fmt:"%d.%m.%Y",
time_fmt:"%H:%M:%S",
insertdate_desc:"Lis\u00E4\u00E4 p\u00E4iv\u00E4m\u00E4\u00E4r\u00E4",
inserttime_desc:"Lis\u00E4\u00E4 kellonaika",
months_long:"Tammikuu,Helmikuu,Maaliskuu,Huhtikuu,Toukokuu,Kes\u00E4kuu,Hein\u00E4kuu,Elokuu,Syyskuu,Lokakuu,Marraskuu,Joulukuu",
months_short:"Tammi,Helmi,Maalis,Huhti,Touko,Kes\u00E4,Hein\u00E4,Elo,Syys,Loka,Marras,Joulu",
day_long:"sunnuntai,maanantai,tiistai,keskiviikko,torstai,perjantai,lauantai,sunnuntai",
day_short:"su,ma,ti,ke,to,pe,la,su"
},
print:{
print_desc:"Tulosta"
},
preview:{
preview_desc:"Esikatselu"
},
directionality:{
ltr_desc:"Suunta vasemmalta oikealle",
rtl_desc:"Suunta oikealta vasemmalle"
},
layer:{
insertlayer_desc:"Lis\u00E4\u00E4 uusi taso",
forward_desc:"Siirr\u00E4 eteenp\u00E4in",
backward_desc:"Siirr\u00E4 taaksep\u00E4in",
absolute_desc:"Absoluuttinen sijainti",
content:"Uusi taso..."
},
save:{
save_desc:"Tallenna",
cancel_desc:"Peruuta kaikki muutokset"
},
nonbreaking:{
nonbreaking_desc:"Lis\u00E4\u00E4 tyhj\u00E4 merkki (nbsp)"
},
iespell:{
iespell_desc:"Oikeinkirjoituksetn tarkistus",
download:"ieSpell ohjelmaa ei havaittu. Haluatko asentaa sen nyt?"
},
advhr:{
advhr_desc:"Vaakataso viivain"
},
emotions:{
emotions_desc:"Hymi\u00F6t"
},
searchreplace:{
search_desc:"Etsi",
replace_desc:"Etsi ja korvaa"
},
advimage:{
image_desc:"Lis\u00E4\u00E4/muokkaa kuvaa"
},
advlink:{
link_desc:"Lis\u00E4\u00E4/muokkaa linkki\u00E4"
},
xhtmlxtras:{
cite_desc:"Sitaatti",
abbr_desc:"Lyhenne",
acronym_desc:"Kirjainlyhenne",
del_desc:"Poisto",
ins_desc:"Lis\u00E4ys",
attribs_desc:"Lis\u00E4\u00E4/muokkaa attribuutteja"
},
style:{
desc:"Muokkaa CSS tyylej\u00E4"
},
paste:{
paste_text_desc:"Liit\u00E4 pelkk\u00E4n\u00E4 tekstin\u00E4",
paste_word_desc:"Liit\u00E4 Wordist\u00E4",
selectall_desc:"Valitse kaikki",
plaintext_mode_sticky:"Paste is now in plain text mode. Click again to toggle back to regular paste mode. After you paste something you will be returned to regular paste mode.",
plaintext_mode:"Paste is now in plain text mode. Click again to toggle back to regular paste mode."
},
paste_dlg:{
text_title:"Paina CTRL+V liitt\u00E4\u00E4ksesi teksti ikkunaan.",
text_linebreaks:"S\u00E4ilyt\u00E4 rivinvaihdot",
word_title:"Paina CTRL+V liitt\u00E4\u00E4ksesi teksti ikkunaan."
},
table:{
desc:"Lis\u00E4\u00E4 uusi taulukko",
row_before_desc:"Lis\u00E4\u00E4 rivi ennen",
row_after_desc:"Lis\u00E4\u00E4 rivi j\u00E4lkeen",
delete_row_desc:"Poista rivi",
col_before_desc:"Lis\u00E4\u00E4 sarake ennen",
col_after_desc:"Lis\u00E4\u00E4 sarake j\u00E4lkeen",
delete_col_desc:"Poista sarake",
split_cells_desc:"Jaa yhdistetyt taulukon solut",
merge_cells_desc:"Yhdist\u00E4 taulukon solut",
row_desc:"Taulukon rivin asetukset",
cell_desc:"Taulukon solun asetukset",
props_desc:"Taulukon asetukset",
paste_row_before_desc:"Liit\u00E4 taulukon rivi ennen",
paste_row_after_desc:"Liit\u00E4 taulukon rivi j\u00E4lkeen",
cut_row_desc:"Leikkaa taulukon rivi",
copy_row_desc:"Kopioi taulukon rivi",
del:"Poista taulukko",
row:"Rivi",
col:"Sarake",
cell:"Solu"
},
autosave:{
unload_msg:"Tekem\u00E4si muutokset menetet\u00E4\u00E4n jos poistut t\u00E4lt\u00E4 sivulta.",
restore_content:"Restore auto-saved content.",
warning_message:"If you restore the saved content, you will lose all the content that is currently in the editor.\n\nAre you sure you want to restore the saved content?."
},
fullscreen:{
desc:"Kokoruututila"
},
media:{
desc:"Lis\u00E4\u00E4/muokkaa upotettua mediaa",
edit:"Muokkaa upotettua mediaa"
},
fullpage:{
desc:"Tiedoston asetukset"
},
template:{
desc:"Lis\u00E4\u00E4 esim\u00E4\u00E4ritetty\u00E4 sivupohja sis\u00E4lt\u00F6\u00E4"
},
visualchars:{
desc:"Visual control characters on/off."
},
spellchecker:{
desc:"Oikeinkirjoituksen tarkistus",
menu:"Oikeinkirjoituksen asetukset",
ignore_word:"Ohita sana",
ignore_words:"Ohita kaikki",
langs:"Kielet",
wait:"Odota ole hyv\u00E4...",
sug:"Ehdotukset",
no_sug:"Ei ehdotuksia",
no_mpell:"Virheit\u00E4 ei l\u00F6ytynyt."
},
pagebreak:{
desc:"Lis\u00E4\u00E4 sivunvaihto."
},
advlist:{
types:"Types",
def:"Default",
lower_alpha:"Lower alpha",
lower_greek:"Lower greek",
lower_roman:"Lower roman",
upper_alpha:"Upper alpha",
upper_roman:"Upper roman",
circle:"Circle",
disc:"Disc",
square:"Square"
}}});
tinyMCE.addI18n('fi.advanced',{
style_select:"Tyylit",
font_size:"Kirjasinkoko",
fontdefault:"Kirjasin",
block:"Muotoilu",
paragraph:"Kappale",
div:"Div",
address:"Osoite",
pre:"Esimuotoiltu (pre)",
h1:"Otsikko 1",
h2:"Otsikko 2",
h3:"Otsikko 3",
h4:"Otsikko 4",
h5:"Otsikko 5",
h6:"Otsikko 6",
blockquote:"Pitk\u00E4 lainaus",
code:"Koodi",
samp:"Koodiesimerkki",
dt:"M\u00E4\u00E4rittelyn ehto ",
dd:"M\u00E4\u00E4rittelyn kuvaus",
bold_desc:"Lihavoitu (Ctrl+B)",
italic_desc:"Kursivoitu (Ctrl+I)",
underline_desc:"Alleviivattu (Ctrl+U)",
striketrough_desc:"Yliviivattu",
justifyleft_desc:"Tasaus vasemmalle",
justifycenter_desc:"Keskitetty",
justifyright_desc:"Tasaus oikealle",
justifyfull_desc:"Tasattu",
bullist_desc:"J\u00E4rjest\u00E4m\u00E4t\u00F6n lista",
numlist_desc:"J\u00E4rjestetty lista",
outdent_desc:"Loitonna",
indent_desc:"Sisenn\u00E4",
undo_desc:"Peru (Ctrl+Z)",
redo_desc:"Tee uudelleen (Ctrl+Y)",
link_desc:"Lis\u00E4\u00E4/muuta linkki",
unlink_desc:"Poista linkki",
image_desc:"Lis\u00E4\u00E4/muuta kuva",
cleanup_desc:"Siisti sekainen koodi",
code_desc:"Muokkaa HTML-koodia",
sub_desc:"Alaindeksi",
sup_desc:"Yl\u00E4indeksi",
hr_desc:"Lis\u00E4\u00E4 vaakasuora viivain",
removeformat_desc:"Poista muotoilu",
custom1_desc:"Oma kuvauksesi t\u00E4h\u00E4n",
forecolor_desc:"Valitse tekstin v\u00E4ri",
backcolor_desc:"Valitse taustan v\u00E4ri",
charmap_desc:"Lis\u00E4\u00E4 erikoismerkki",
visualaid_desc:"Suuntaviivat/N\u00E4kym\u00E4tt\u00F6m\u00E4t elementit",
anchor_desc:"Lis\u00E4\u00E4/Muokkaa ankkuri",
cut_desc:"Leikkaa",
copy_desc:"Kopioi",
paste_desc:"Liit\u00E4",
image_props_desc:"Kuvan ominaisuudet",
newdocument_desc:"Uusi tiedosto",
help_desc:"Ohje",
blockquote_desc:"Pitk\u00E4 lainaus",
clipboard_msg:"Kopioi/Leikkaa/Liit\u00E4 -painikkeet eiv\u00E4t toimi Mozilla ja Firefox -selaimilla. Voit kuitenkin k\u00E4ytt\u00E4\u00E4 n\u00E4pp\u00E4inyhdistelmi\u00E4 kopioimiseen (ctrl+c), leikkaamiseen (ctrl+x) ja liitt\u00E4miseen (ctrl+v). Haluatko lis\u00E4\u00E4 tietoa?",
path:"Polku",
newdocument:"Haluatko varmasti tyhjent\u00E4\u00E4 kaiken sis\u00E4ll\u00F6n?",
toolbar_focus:"Siirry ty\u00F6kaluihin - Alt+Q, Siirry tekstieditoriin - Alt-Z, Siirry elementin polkuun - Alt-X",
more_colors:"Enemm\u00E4n v\u00E4rej\u00E4"
});
tinyMCE.addI18n('fi.advanced_dlg',{
about_title:"Tietoja TinyMCE:st\u00E4",
about_general:"Tietoja",
about_help:"Ohje",
about_license:"Lisenssi",
about_plugins:"Lis\u00E4osat",
about_plugin:"Lis\u00E4osa",
about_author:"Kirjoittaja",
about_version:"Versio",
about_loaded:"Ladatut lis\u00E4osat",
anchor_title:"Liit\u00E4/muokkaa ankkuria",
anchor_name:"Ankkurin nimi",
code_title:"HTML-koodin muokkaus",
code_wordwrap:"Automaattinen rivinvaihto",
colorpicker_title:"Valitse v\u00E4ri",
colorpicker_picker_tab:"Valitsin",
colorpicker_picker_title:"V\u00E4rin valitsin",
colorpicker_palette_tab:"Paletti",
colorpicker_palette_title:"V\u00E4ripalette",
colorpicker_named_tab:"Nimetty",
colorpicker_named_title:"Nimetyt v\u00E4rit",
colorpicker_color:"V\u00E4ri:",
colorpicker_name:"Nimi:",
charmap_title:"Valitse erikoismerkki",
image_title:"Lis\u00E4\u00E4/muokkaa kuvaa",
image_src:"Kuvan osoite",
image_alt:"Kuvan kuvaus",
image_list:"Kuvalista",
image_border:"Reunus",
image_dimensions:"Mitat",
image_vspace:"Pystysuuntainen tila",
image_hspace:"Vaakasuuntainen tila",
image_align:"Tasaus",
image_align_baseline:"Tekstin tasossa",
image_align_top:"Yl\u00F6s",
image_align_middle:"Keskelle",
image_align_bottom:"Alas",
image_align_texttop:"Tekstin yl\u00E4osaan",
image_align_textbottom:"Tekstin alaosaan",
image_align_left:"Vasemmalle",
image_align_right:"Oikealle",
link_title:"Lis\u00E4\u00E4/muuta linkki",
link_url:"Linkin osoite",
link_target:"Kohde",
link_target_same:"Avaa linkki samassa ikkunassa",
link_target_blank:"Avaa linkki uuteen ikkunaan",
link_titlefield:"Otsikko",
link_is_email:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 olevan s\u00E4\u00E4hk\u00F6postiosoite. Haluatko lis\u00E4t\u00E4 siihen mailto:-etuliitteen?",
link_is_external:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 johtavan ulkopuoliselle sivustolle. Haluatko lis\u00E4t\u00E4 linkin eteen http://-etuliitteen? (suositus)",
link_list:"Linkkilista"
});
tinyMCE.addI18n('fi.advimage_dlg',{
tab_general:"Yleiset",
tab_appearance:"N\u00E4kyminen",
tab_advanced:"Edistynyt",
general:"Yleiset",
title:"Otsikko",
preview:"Esikatselu",
constrain_proportions:"S\u00E4ilyt\u00E4 mittasuhteet",
langdir:"Kielen suunta",
langcode:"Kielen koodi",
long_desc:"Pitk\u00E4n kuvauksen linkki",
style:"Tyyli",
classes:"Luokat",
ltr:"Vasemmalta oikealle",
rtl:"Oikealta vasemmalle",
id:"Id",
map:"Kuvakartta",
swap_image:"Vaihda kuva",
alt_image:"Vaihtoehtoinen kuva",
mouseover:"mouseoverille",
mouseout:"mouseoutille",
misc:"Sekalaiset",
example_img:"Ulkoasun esikatselukuva",
missing_alt:"Haluako varmasti jatkaa lis\u00E4\u00E4m\u00E4tt\u00E4 kuvausta? Sen puuttumuinen saattaa h\u00E4irit\u00E4 sellaisia, jotka k\u00E4ytt\u00E4v\u00E4t tekstipohjaista selainta tai ovat kytkeneet kuvien n\u00E4kymisen pois p\u00E4\u00E4lt\u00E4.",
dialog_title:"Lis\u00E4\u00E4/muokkaa kuvaa",
src:"Kuvan URL",
alt:"Kuvan kuvaus",
list:"Kuvalista",
border:"Kehys",
dimensions:"Mitat",
vspace:"pystysuora tila",
hspace:"vaakasuora tila",
align:"Tasaus",
align_baseline:"Rivill\u00E4",
align_top:"Ylh\u00E4\u00E4ll\u00E4",
align_middle:"Keskell\u00E4",
align_bottom:"Alhaalla",
align_texttop:"Teksti ylh\u00E4\u00E4ll\u00E4",
align_textbottom:"Teksti alhaalla",
align_left:"Vasemmalla",
align_right:"Oikealla",
image_list:"Kuvalista"
});
tinyMCE.addI18n('fi.advlink_dlg',{
title:"Lis\u00E4\u00E4/muokkaa linkki\u00E4",
url:"Linkin URL",
target:"Kohde (target)",
titlefield:"Otsikko",
is_email:"Sy\u00F6tt\u00E4m\u00E4si URL n\u00E4ytt\u00E4\u00E4 olevan s\u00E4hk\u00F6postiosoite, haluatko lis\u00E4t\u00E4 mailto:-etuliitteen?",
is_external:"Sy\u00F6tt\u00E4m\u00E4si URL n\u00E4ytt\u00E4\u00E4 olevan sivuston ulkoinen osoite, haluatko lis\u00E4t\u00E4 http://-etuliitteen?",
list:"Linkkilista",
general_tab:"Yleiset",
popup_tab:"Ponnahdusikkuna",
events_tab:"Tapahtumat",
advanced_tab:"Edistynyt",
general_props:"Yleiset asetukset",
popup_props:"Ponnahdusikkunan asetukset",
event_props:"Tapahtumat (events)",
advanced_props:"Edistyneet asetukset",
popup_opts:"Valinta",
anchor_names:"Ankkurit",
target_same:"Avaa t\u00E4ss\u00E4 ikkunassa",
target_parent:"Avaa ylemm\u00E4ss\u00E4 ikkunassa",
target_top:"Avaa ylimm\u00E4ss\u00E4 ruudussa (korvaa kaikki ruudut)",
target_blank:"Avaa uudessa ikkunassa",
popup:"Javascript ponnahdusikkuna",
popup_url:"Ponnahdusikkunan URL",
popup_name:"Ikkunan nimi",
popup_return:"Lis\u00E4\u00E4 'return false'",
popup_scrollbars:"N\u00E4yt\u00E4 vierityspalkit",
popup_statusbar:"N\u00E4yt\u00E4 tilapalkki",
popup_toolbar:"N\u00E4yt\u00E4 ty\u00F6kalut",
popup_menubar:"N\u00E4yt\u00E4 valikkopalkki",
popup_location:"N\u00E4yt\u00E4 sijaintipalkki",
popup_resizable:"Tee ikkunan koko muokattavaksi",
popup_dependent:"Riippuvainen (vain Mozilla/Firefox)",
popup_size:"Koko",
popup_position:"Sijainti (X/Y)",
id:"Id",
style:"Tyyli",
classes:"Luokat",
target_name:"Kohteen nimi",
langdir:"Kielen suunta",
target_langcode:"Kohteen kieli",
langcode:"Kielen koodi",
encoding:"Kohteen merkist\u00F6koodaus",
mime:"Kohteen MIME-tyyppi",
rel:"Sivun suhde kohteeseen",
rev:"Kohteen suhde sivuun",
tabindex:"Tabulaattori-indeksi",
accesskey:"Pikan\u00E4pp\u00E4in",
ltr:"Vasemmalta oikealle",
rtl:"Oikealta vasemmalle",
link_list:"Linkkilista"
});
tinyMCE.addI18n('fi.emotions_dlg',{
title:"Lis\u00E4\u00E4 hymi\u00F6",
desc:"Hymi\u00F6t",
cool:"Cool",
cry:"Itku",
embarassed:"Nolostunut",
foot_in_mouth:"Jalka suussa",
frown:"Otsan rypistys",
innocent:"Viaton",
kiss:"Pusu",
laughing:"Nauru",
money_mouth:"Klink Klink (raha)",
sealed:"Tukittu",
smile:"Hymy",
surprised:"Yll\u00E4ttynyt",
tongue_out:"Kieli ulkona",
undecided:"P\u00E4\u00E4tt\u00E4m\u00E4t\u00F6n",
wink:"Silm\u00E4nisku",
yell:"Huuto"
});
tinyMCE.addI18n('fi.media_dlg',{
title:"Lis\u00E4\u00E4/muokkaa upotettua mediaa",
general:"Yleiset",
advanced:"Edistyneet",
file:"Tiedosto/URL",
list:"Lista",
size:"Mitat",
preview:"Esikatselu",
constrain_proportions:"S\u00E4ilyt\u00E4 mittasuhteet",
type:"Tyyppi",
id:"Id",
name:"Name",
class_name:"Luokka",
vspace:"Pystytason tila",
hspace:"Vaakatason tila",
play:"Automaattinen toisto",
loop:"Silmukka",
menu:"N\u00E4yt\u00E4 valikko",
quality:"Laatu",
scale:"Skaala",
align:"Tasaus",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Tausta",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"V\u00E4limuisti",
hidden:"Piilotettu",
controller:"Ohjain",
kioskmode:"Kioski-tila",
playeveryframe:"Toista jokainen ruutu",
targetcache:"Kohteen v\u00E4limuisti",
correction:"Ei korjausta",
enablejavascript:"Salli JavaScript",
starttime:"Aloitus aika",
endtime:"Lopetus aika",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Kohde",
volume:"\u00C4\u00E4nen voimakkuus",
autostart:"Automaattinen aloitus",
enabled:"P\u00E4\u00E4ll\u00E4",
fullscreen:"Kokoruutu",
invokeurls:"Invoke URLs",
mute:"Mute",
stretchtofit:"Venyt\u00E4 sopimaan",
windowlessvideo:"Ikkunaton video",
balance:"Tasapaino",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Default frame",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Flash options",
qt_options:"Quicktime options",
wmp_options:"Windows media player options",
rmp_options:"Real media player options",
shockwave_options:"Shockwave options",
autogotourl:"Auto goto URL",
center:"Center",
imagestatus:"Image status",
maintainaspect:"Maintain aspect",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Controls",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Top",
align_right:"Right",
align_bottom:"Bottom",
align_left:"Left",
align_center:"Center",
align_top_left:"Top left",
align_top_right:"Top right",
align_bottom_left:"Bottom left",
align_bottom_right:"Bottom right",
flv_options:"Flash video options",
flv_scalemode:"Scale mode",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Start time",
flv_defaultvolume:"Default volumne",
flv_hiddengui:"Hidden GUI",
flv_autostart:"Auto start",
flv_loop:"Loop",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});
tinyMCE.addI18n('fi.paste_dlg',{
text_title:"Paina CTRL+V liitt\u00E4\u00E4ksesi teksti ikkunaan.",
text_linebreaks:"S\u00E4ilyt\u00E4 rivinvaihdot",
word_title:"Paina CTRL+V liitt\u00E4\u00E4ksesi teksti ikkunaan."
});
tinyMCE.addI18n('fi.searchreplace_dlg',{
searchnext_desc:"Etsi uudestaan",
notfound:"Haku on valmis. Haettua teksti\u00E4 ei l\u00F6ytynyt.",
search_title:"Haku",
replace_title:"Etsi ja korvaa",
allreplaced:"Kaikki l\u00F6ydetyt merkkijonot korvattiin.",
findwhat:"Etsit\u00E4\u00E4n",
replacewith:"Korvataan",
direction:"Suunta",
up:"Yl\u00F6s",
down:"Alas",
mcase:"Huomioi isot ja pienet kirjaimet",
findnext:"Etsi seuraavaa",
replace:"Korvaa",
replaceall:"Korvaa kaikki"
});
tinyMCE.addI18n('fi.style_dlg',{
title:"Muokkaa CSS-tyyli\u00E4",
apply:"K\u00E4yt\u00E4",
text_tab:"Teksti",
background_tab:"Tausta",
block_tab:"Palkki",
box_tab:"Laatikko",
border_tab:"Kehys",
list_tab:"Lista",
positioning_tab:"Sijainti",
text_props:"Teksti",
text_font:"Kirjasin",
text_size:"Koko",
text_weight:"Paino",
text_style:"Tyyli",
text_variant:"Variantti",
text_lineheight:"Rivin korkeus",
text_case:"Isot/pienet kirjaimet",
text_color:"V\u00E4ri",
text_decoration:"Koristelu",
text_overline:"Ylleviivattu",
text_underline:"Alleviivattu (Ctrl+U)",
text_striketrough:"Yliviivattu",
text_blink:"V\u00E4l\u00E4hdys",
text_none:"ei mit\u00E4\u00E4n",
background_color:"Taustav\u00E4ri",
background_image:"Taustakuva",
background_repeat:"Toistuvuus",
background_attachment:"Liite",
background_hpos:"Vaaka-asettelu",
background_vpos:"Pystyasettelu",
block_wordspacing:"Sanojen v\u00E4listys",
block_letterspacing:"Kirjainten v\u00E4listys",
block_vertical_alignment:"Pystyasettelu",
block_text_align:"Tekstin asettelu",
block_text_indent:"Tekstin sisennys",
block_whitespace:"Tyhj\u00E4 tila",
block_display:"N\u00E4ytt\u00F6",
box_width:"Leveys",
box_height:"Korkeus",
box_float:"Kellunta",
box_clear:"Nollaus",
padding:"Tyhj\u00E4 tila",
same:"Sama kaikille",
top:"Ylh\u00E4\u00E4ll\u00E4",
right:"Oikealla",
bottom:"Alhaalla",
left:"Vasemmalla",
margin:"Marginaali",
style:"Tyyli",
width:"Leveys",
height:"Korkeus",
color:"V\u00E4ri",
list_type:"Tyyppi",
bullet_image:"Listauskuva",
position:"Sijainti",
positioning_type:"Tyyppi",
visibility:"N\u00E4kyvyys",
zindex:"Z-indeksi",
overflow:"Ylivuoto",
placement:"Sijoittelu",
clip:"Leike"
});