tinyMCE.addI18n({fr:{
common:{
edit_confirm:"Souhaitez-vous utiliser le mode WYSIWYG pour cette zone de texte ?",
apply:"Appliquer",
insert:"Ins\u00E9rer",
update:"Mettre \u00E0 jour",
cancel:"Annuler",
close:"Fermer",
browse:"parcourir",
class_name:"Class",
not_set:"-- non d\u00E9fini --",
clipboard_msg:"Les fonctions Copier/Couper/Coller ne sont pas valables sur Mozilla et Firefox.\nSouhaitez-vous avoir plus d'informations sur ce sujet ?",
clipboard_no_support:"Actuellement non support\u00E9 par votre navigateur.\n Veuillez utiliser les raccourcis clavier \u00E0 la place.",
popup_blocked:"D\u00E9sol\u00E9, nous avons d\u00E9tect\u00E9 que votre bloqueur de popup a bloqu\u00E9 une fen\u00EAtre dont l'application a besoin. Vous devez d\u00E9sactiver votre bloqueur de popup pour pouvoir utiliser cet outil.",
invalid_data:"Erreur : saisie de valeurs incorrectes. Elles sont mises en \u00E9vidence en rouge.",
more_colors:"Plus de couleurs"
},
contextmenu:{
align:"Alignement",
left:"Gauche",
center:"Centr\u00E9",
right:"Droite",
full:"Justifi\u00E9"
},
insertdatetime:{
date_fmt:"%d-%m-%Y",
time_fmt:"%H:%M:%S",
insertdate_desc:"Ins\u00E9rer la date",
inserttime_desc:"Ins\u00E9rer l'heure",
months_long:"Janvier,F\u00E9vrier,Mars,Avril,Mai,Juin,Juillet,Ao\u00FBt,Septembre,Octobre,Novembre,D\u00E9cembre",
months_short:"Jan,F\u00E9v,Mar,Avr,Mai,Juin,Juil,Ao\u00FBt,Sep,Oct,Nov,D\u00E9c",
day_long:"Dimanche,Lundi,Mardi,Mercredi,Jeudi,Vendredi,Samedi,Dimanche",
day_short:"Dim,Lun,Mar,Mer,Jeu,Ven,Sam,Dim"
},
print:{
print_desc:"Imprimer"
},
preview:{
preview_desc:"Pr\u00E9visualiser"
},
directionality:{
ltr_desc:"\u00C9criture de gauche \u00E0 droite",
rtl_desc:"\u00C9criture de droite \u00E0 gauche"
},
layer:{
insertlayer_desc:"Ins\u00E9rer une nouvelle couche",
forward_desc:"D\u00E9placer vers l'avant",
backward_desc:"D\u00E9placer vers l'arri\u00E8re",
absolute_desc:"Activer le positionnement absolu",
content:"Nouvelle couche\u2026"
},
save:{
save_desc:"Enregistrer",
cancel_desc:"Annuler toutes les modifications"
},
nonbreaking:{
nonbreaking_desc:"Ins\u00E9rer une espace ins\u00E9cable"
},
iespell:{
iespell_desc:"Lancer le v\u00E9rificateur d'orthographe",
download:"ieSpell n'est pas install\u00E9. Souhaitez-vous l'installer maintenant ?"
},
advhr:{
advhr_desc:"Ins\u00E9rer un trait horizontal"
},
emotions:{
emotions_desc:"\u00C9motic\u00F4nes"
},
searchreplace:{
search_desc:"Rechercher",
replace_desc:"Rechercher / remplacer"
},
advimage:{
image_desc:"Ins\u00E9rer / \u00E9diter une image"
},
advlink:{
link_desc:"Ins\u00E9rer / \u00E9diter un lien"
},
xhtmlxtras:{
cite_desc:"Citation",
abbr_desc:"Abr\u00E9viation",
acronym_desc:"Acronyme",
del_desc:"Barr\u00E9",
ins_desc:"Ins\u00E9r\u00E9",
attribs_desc:"Ins\u00E9rer / \u00E9diter les attributs"
},
style:{
desc:"\u00C9diter la feuille de style (CSS)"
},
paste:{
paste_text_desc:"Coller comme texte brut",
paste_word_desc:"Coller un texte cr\u00E9\u00E9 sous Word",
selectall_desc:"Tout s\u00E9lectionner",
plaintext_mode_sticky:"Le collage est actuellement en mode texte non format\u00E9. Cliquez \u00E0 nouveau pour revenir en mode de collage ordinaire. Apr\u00E8s avoir coll\u00E9 quelque chose, vous retournerez en mode de collage ordinaire.",
plaintext_mode:"Le collage est actuellement en mode texte non format\u00E9. Cliquez \u00E0 nouveau pour revenir en mode de collage ordinaire."
},
paste_dlg:{
text_title:"Utilisez CTRL+V sur votre clavier pour coller le texte dans la fen\u00EAtre.",
text_linebreaks:"Conserver les retours \u00E0 la ligne",
word_title:"Utilisez CTRL+V sur votre clavier pour coller le texte dans la fen\u00EAtre."
},
table:{
desc:"Ins\u00E9rer un nouveau tableau",
row_before_desc:"Ins\u00E9rer une ligne avant",
row_after_desc:"Ins\u00E9rer une ligne apr\u00E8s",
delete_row_desc:"Effacer la ligne",
col_before_desc:"Ins\u00E9rer une colonne avant",
col_after_desc:"Ins\u00E9rer une colonne apr\u00E8s",
delete_col_desc:"Effacer la colonne",
split_cells_desc:"Scinder les cellules fusionn\u00E9es",
merge_cells_desc:"Fusionner les cellules",
row_desc:"Propri\u00E9t\u00E9s de la ligne",
cell_desc:"Propri\u00E9t\u00E9s de la cellule",
props_desc:"Propri\u00E9t\u00E9s du tableau",
paste_row_before_desc:"Coller la ligne avant",
paste_row_after_desc:"Coller la ligne apr\u00E8s",
cut_row_desc:"Couper la ligne",
copy_row_desc:"Copier la ligne",
del:"Effacer le tableau",
row:"Ligne",
col:"Colonne",
cell:"Cellule"
},
autosave:{
unload_msg:"Les modifications apport\u00E9es seront perdus si vous quittez cette page.",
restore_content:"Restaurer le contenu auto-sauvegard\u00E9.",
warning_message:"Si vous restaurez le contenu sauv\u00E9, vous perdrez le contenu qui est actuellement dans l'\u00E9diteur.\n\n\u00CAtes-vous s\u00FBr de vouloir restaurer le contenu sauv\u00E9 ?"
},
fullscreen:{
desc:"Passer en mode plein \u00E9cran"
},
media:{
desc:"Ins\u00E9rer / \u00E9diter un m\u00E9dia incorpor\u00E9",
edit:"\u00C9diter un m\u00E9dia incorpor\u00E9"
},
fullpage:{
desc:"Propri\u00E9t\u00E9s du document"
},
template:{
desc:"Ins\u00E9rer un mod\u00E8le pr\u00E9d\u00E9fini."
},
visualchars:{
desc:"Activer les caract\u00E8res de mise en page."
},
spellchecker:{
desc:"Activer le v\u00E9rificateur d'orthographe",
menu:"Param\u00E8tres du v\u00E9rificateur d'orthographe",
ignore_word:"Ignorer le mot",
ignore_words:"Tout ignorer",
langs:"Langues",
wait:"Veuillez patienter\u2026",
sug:"Suggestions",
no_sug:"Aucune suggestion",
no_mpell:"Aucune erreur trouv\u00E9e."
},
pagebreak:{
desc:"Ins\u00E9rer un saut de page."
},
advlist:{
types:"Types",
def:"Defaut",
lower_alpha:"Alpha minuscule",
lower_greek:"Grec minuscule",
lower_roman:"Romain minuscule",
upper_alpha:"Alpha majuscule",
upper_roman:"Romain majuscule",
circle:"Cercle",
disc:"Disque",
square:"Carr\u00E9"
}}});
tinyMCE.addI18n('fr.advanced',{
style_select:"Styles",
font_size:"Taille police",
fontdefault:"Police",
block:"Format",
paragraph:"Paragraphe",
div:"Div",
address:"Adresse",
pre:"Pr\u00E9format\u00E9",
h1:"Titre 1",
h2:"Titre 2",
h3:"Titre 3",
h4:"Titre 4",
h5:"Titre 5",
h6:"Titre 6",
blockquote:"Bloc de citation",
code:"Code",
samp:"Exemple de code",
dt:"Terme \u00E0 d\u00E9finir",
dd:"D\u00E9finition du terme",
bold_desc:"Gras (Ctrl+B)",
italic_desc:"Italique (Ctrl+I)",
underline_desc:"Soulign\u00E9 (Ctrl+U)",
striketrough_desc:"Barr\u00E9",
justifyleft_desc:"Align\u00E9 \u00E0 gauche",
justifycenter_desc:"Centr\u00E9",
justifyright_desc:"Align\u00E9 \u00E0 droite",
justifyfull_desc:"Justifi\u00E9",
bullist_desc:"Liste \u00E0 puces",
numlist_desc:"Liste num\u00E9rot\u00E9e",
outdent_desc:"Retirer l'indentation",
indent_desc:"Indenter",
undo_desc:"Annuler (Ctrl+Z)",
redo_desc:"R\u00E9tablir (Ctrl+Y)",
link_desc:"Ins\u00E9rer / \u00E9diter le lien",
unlink_desc:"Supprimer le lien",
image_desc:"Ins\u00E9rer / \u00E9diter l'image",
cleanup_desc:"Nettoyer le code",
code_desc:"\u00C9diter le code source HTML",
sub_desc:"Indice",
sup_desc:"Exposant",
hr_desc:"Ins\u00E9rer un trait horizontal",
removeformat_desc:"Supprimer le formatage",
custom1_desc:"Votre description personnalis\u00E9e ici",
forecolor_desc:"Choisir la couleur du texte",
backcolor_desc:"Choisir la couleur de surlignage",
charmap_desc:"Ins\u00E9rer des caract\u00E8res sp\u00E9ciaux",
visualaid_desc:"Activer / d\u00E9sactiver les guides et les \u00E9l\u00E9ments invisibles",
anchor_desc:"Ins\u00E9rer / \u00E9diter une ancre",
cut_desc:"Couper",
copy_desc:"Copier",
paste_desc:"Coller",
image_props_desc:"Propri\u00E9t\u00E9s de l'image",
newdocument_desc:"Nouveau document",
help_desc:"Aide",
blockquote_desc:"Citation",
clipboard_msg:"Les fonctions Copier/Couper/Coller ne sont pas valables sur Mozilla et Firefox.\nSouhaitez-vous avoir plus d'informations sur ce sujet ?",
path:"Chemin",
newdocument:"\u00CAtes-vous s\u00FBr de vouloir effacer l'int\u00E9gralit\u00E9 du document ?",
toolbar_focus:"Atteindre les boutons de l'\u00E9diteur - Alt+Q, Aller \u00E0 l'\u00E9diteur - Alt-Z, Aller au chemin de l'\u00E9l\u00E9ment - Alt-X",
more_colors:"Plus de couleurs"
});
tinyMCE.addI18n('fr.advanced_dlg',{
about_title:"\u00C0 propos de TinyMCE",
about_general:"\u00C0 propos",
about_help:"Aide",
about_license:"Licence",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Auteur",
about_version:"Version",
about_loaded:"Plugins charg\u00E9s",
anchor_title:"Ins\u00E9rer / \u00E9diter une ancre",
anchor_name:"Nom de l'ancre",
code_title:"\u00C9diteur de source HTML",
code_wordwrap:"Retour \u00E0 la ligne",
colorpicker_title:"Choisir une couleur",
colorpicker_picker_tab:"Nuancier",
colorpicker_picker_title:"Nuancier",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Couleurs de la palette",
colorpicker_named_tab:"Noms",
colorpicker_named_title:"Couleurs nomm\u00E9es",
colorpicker_color:"Couleur :",
colorpicker_name:"Nom :",
charmap_title:"Choisir le caract\u00E8re \u00E0 ins\u00E9rer",
image_title:"Ins\u00E9rer / \u00E9diter une image",
image_src:"URL de l'image",
image_alt:"Description de l'image",
image_list:"Liste d'images",
image_border:"Bordure",
image_dimensions:"Dimensions",
image_vspace:"Espacement vertical",
image_hspace:"Espacement horizontal",
image_align:"Alignement",
image_align_baseline:"Normal",
image_align_top:"En haut",
image_align_middle:"Au milieu",
image_align_bottom:"En bas",
image_align_texttop:"Texte en haut",
image_align_textbottom:"Texte en bas",
image_align_left:"Gauche (flottant)",
image_align_right:"Droite (flottant)",
link_title:"Ins\u00E9rer / \u00E9diter un lien",
link_url:"URL du lien",
link_target:"Cible",
link_target_same:"Ouvrir dans la m\u00EAme fen\u00EAtre",
link_target_blank:"Ouvrir dans une nouvelle fen\u00EAtre",
link_titlefield:"Titre",
link_is_email:"L'URL que vous avez saisie semble \u00EAtre une adresse e-mail, souhaitez-vous ajouter le pr\u00E9fixe \u00AB mailto: \u00BB ?",
link_is_external:"L'URL que vous avez saisie semble \u00EAtre une adresse web externe. Souhaitez-vous ajouter le pr\u00E9fixe \u00AB http:// \u00BB ?",
link_list:"Liste de liens"
});
tinyMCE.addI18n('fr.advimage_dlg',{
tab_general:"G\u00E9n\u00E9ral",
tab_appearance:"Apparence",
tab_advanced:"Avanc\u00E9",
general:"G\u00E9n\u00E9ral",
title:"Titre",
preview:"Pr\u00E9visualisation",
constrain_proportions:"Conserver les proportions",
langdir:"Sens de lecture",
langcode:"Code de la langue",
long_desc:"Description longue du lien",
style:"Style",
classes:"Classes",
ltr:"De gauche \u00E0 droite",
rtl:"De droite \u00E0 gauche",
id:"Id",
map:"Image cliquable",
swap_image:"Image de remplacement",
alt_image:"Image alternative",
mouseover:"au survol de la souris",
mouseout:"\u00E0 la sortie de la souris",
misc:"Divers",
example_img:"Apparence de l'image",
missing_alt:"\u00CAtes-vous s\u00FBr de vouloir continuer sans d\u00E9finir de description pour l'image ? Sans elle, l'image peut ne pas \u00EAtre accessible \u00E0 certains utilisateurs handicap\u00E9s, ceux utilisant un navigateur texte ou ceux qui naviguent sans affichage des images.",
dialog_title:"Ins\u00E9rer / \u00E9diter une image",
src:"URL de l'image",
alt:"Description de l'image",
list:"Liste d'images",
border:"Bordure",
dimensions:"Dimensions",
vspace:"Espacement vertical",
hspace:"Espacement horizontal",
align:"Alignement",
align_baseline:"Normal",
align_top:"En haut",
align_middle:"Au milieu",
align_bottom:"En bas",
align_texttop:"Texte en haut",
align_textbottom:"Texte en bas",
align_left:"Gauche (flottant)",
align_right:"Droite (flottant)",
image_list:"Liste d'images"
});
tinyMCE.addI18n('fr.advlink_dlg',{
title:"Ins\u00E9rer / \u00E9diter un lien",
url:"URL du lien",
target:"Cible",
titlefield:"Titre",
is_email:"L'URL que vous avez saisie semble \u00EAtre une adresse e-mail, souhaitez-vous ajouter le pr\u00E9fixe \u00AB mailto: \u00BB ?",
is_external:"L'URL que vous avez saisie semble \u00EAtre une adresse web externe. Souhaitez-vous ajouter le pr\u00E9fixe \u00AB http:// \u00BB ?",
list:"Liste de liens",
general_tab:"G\u00E9n\u00E9ral",
popup_tab:"Popup",
events_tab:"\u00C9v\u00E8nements",
advanced_tab:"Avanc\u00E9",
general_props:"Propri\u00E9t\u00E9s g\u00E9n\u00E9rales",
popup_props:"Propri\u00E9t\u00E9s de la popup",
event_props:"\u00C9v\u00E8nements",
advanced_props:"Propri\u00E9t\u00E9s avanc\u00E9es",
popup_opts:"Options",
anchor_names:"Ancres",
target_same:"Ouvrir dans cette fen\u00EAtre / dans ce cadre",
target_parent:"Ouvrir dans la fen\u00EAtre / le cadre parent",
target_top:"Ouvrir dans le cadre principal (remplace tous les cadres)",
target_blank:"Ouvrir dans une nouvelle fen\u00EAtre",
popup:"Popup Javascript",
popup_url:"URL de la popup",
popup_name:"Nom de la fen\u00EAtre",
popup_return:"Ins\u00E9rer 'return false'",
popup_scrollbars:"Afficher les ascenseurs",
popup_statusbar:"Afficher la barre d'\u00E9tat",
popup_toolbar:"Afficher la barre d'outils",
popup_menubar:"Afficher la barre de menu",
popup_location:"Afficher la barre d'adresse",
popup_resizable:"Autoriser le redimensionnement de la fen\u00EAtre",
popup_dependent:"D\u00E9pendante (seulement sous Mozilla/Firefox)",
popup_size:"Taille",
popup_position:"Position (X/Y)",
id:"Id",
style:"Style",
classes:"Classes",
target_name:"Nom de la cible",
langdir:"Sens de lecture",
target_langcode:"Langue de la cible",
langcode:"Code de la langue",
encoding:"Encodage de la cible",
mime:"Type MIME de la cible",
rel:"Relation de la page \u00E0 la cible",
rev:"Relation de la cible \u00E0 la page",
tabindex:"Tabindex",
accesskey:"Touche d'acc\u00E8s rapide",
ltr:"Gauche \u00E0 droite",
rtl:"Droite \u00E0 gauche",
link_list:"Liste des liens"
});
tinyMCE.addI18n('fr.emotions_dlg',{
title:"Ins\u00E9rer une \u00E9motic\u00F4ne",
desc:"\u00C9motic\u00F4nes",
cool:"Cool",
cry:"En pleurs",
embarassed:"Embarrass\u00E9",
foot_in_mouth:"Pied de nez",
frown:"D\u00E9\u00E7u",
innocent:"Innocent",
kiss:"Bisou",
laughing:"Rigolant",
money_mouth:"Avare",
sealed:"Bouche cousue",
smile:"Sourire",
surprised:"Surpris",
tongue_out:"Langue tir\u00E9e",
undecided:"Incertain",
wink:"Clin d'\u0153il",
yell:"Criant"
});
tinyMCE.addI18n('fr.media_dlg',{
title:"Ins\u00E9rer / \u00E9diter un fichier m\u00E9dia",
general:"G\u00E9n\u00E9ral",
advanced:"Avanc\u00E9",
file:"Fichier / URL",
list:"Liste",
size:"Dimensions",
preview:"Pr\u00E9visualisation",
constrain_proportions:"Conserver les proportions",
type:"Type",
id:"Id",
name:"Nom",
class_name:"Classe",
vspace:"Espacement vertical",
hspace:"Espacement horizontal",
play:"Lecture automatique",
loop:"Lire en boucle",
menu:"Afficher le menu",
quality:"Qualit\u00E9",
scale:"\u00C9chelle",
align:"Alignement",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fond",
base:"Base",
flashvars:"Variables flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Cach\u00E9",
controller:"Contr\u00F4leur",
kioskmode:"Mode kiosque",
playeveryframe:"Jouer toutes les images",
targetcache:"Cache cible",
correction:"Pas de correction",
enablejavascript:"Activer le JavaScript",
starttime:"D\u00E9but",
endtime:"Fin",
href:"Href",
qtsrcchokespeed:"D\u00E9bit maximum",
target:"Cible",
volume:"Volume",
autostart:"Lire automatiquement",
enabled:"Activ\u00E9",
fullscreen:"Plein \u00E9cran",
invokeurls:"Invoquer URLs",
mute:"Muet",
stretchtofit:"\u00C9tendre pour adapter la taille",
windowlessvideo:"Vid\u00E9o sans fen\u00EAtre",
balance:"Balance",
baseurl:"Adresse de base",
captioningid:"Captioning id",
currentmarker:"Marqueur actuel",
currentposition:"Position actuelle",
defaultframe:"Image par d\u00E9faut",
playcount:"Compteur",
rate:"Taux",
uimode:"Mode UI",
flash_options:"Options Flash",
qt_options:"Options Quicktime",
wmp_options:"Windows media player options",
rmp_options:"Options Real media player",
shockwave_options:"Options Shockwave",
autogotourl:"Aller automatiquement \u00E0 l'URL",
center:"Centrer",
imagestatus:"Statut de l'image",
maintainaspect:"Maintenir l'aspect",
nojava:"Pas java",
prefetch:"Pr\u00E9chargement",
shuffle:"Al\u00E9atoire",
console:"Console",
numloop:"Nombre de tours",
controls:"Contr\u00F4les",
scriptcallbacks:"Callback de script",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch horizontal",
swstretchvalign:"Stretch vertical",
sound:"Son",
progress:"Progression",
qtsrc:"Source QT",
qt_stream_warn:"Les ressources rtsp en streaming doivent \u00EAtre ajout\u00E9es au champ \u00AB Source QT \u00BB dans l'onglet avanc\u00E9.\nVous devriez aussi ajouter une version n'\u00E9tant pas en streaming au champ \u00AB source QT \u00BB.",
align_top:"Haut",
align_right:"Droite",
align_bottom:"Bas",
align_left:"Gauche",
align_center:"Centr\u00E9",
align_top_left:"En haut \u00E0 gauche",
align_top_right:"En haut \u00E0 droite",
align_bottom_left:"En bas \u00E0 gauche",
align_bottom_right:"En bas \u00E0 droite",
flv_options:"Options de la vid\u00E9o Flash",
flv_scalemode:"\u00C9chelle",
flv_buffer:"Tampon",
flv_startimage:"Image de d\u00E9marrage",
flv_starttime:"Temps au d\u00E9but",
flv_defaultvolume:"Volume par d\u00E9faut",
flv_hiddengui:"Interface utilisateur cach\u00E9e",
flv_autostart:"D\u00E9marrage automatique",
flv_loop:"En boucle",
flv_showscalemodes:"Montrer les diff\u00E9rentes \u00E9chelles",
flv_smoothvideo:"Vid\u00E9o adoucie",
flv_jscallback:"Callback JavaScript"
});
tinyMCE.addI18n('fr.paste_dlg',{
text_title:"Utilisez CTRL+V sur votre clavier pour coller le texte dans la fen\u00EAtre.",
text_linebreaks:"Conserver les retours \u00E0 la ligne",
word_title:"Utilisez CTRL+V sur votre clavier pour coller le texte dans la fen\u00EAtre."
});
tinyMCE.addI18n('fr.searchreplace_dlg',{
searchnext_desc:"Suivant",
notfound:"La recherche est termin\u00E9e. La cha\u00EEne recherch\u00E9e n'a pas \u00E9t\u00E9 trouv\u00E9e.",
search_title:"Rechercher",
replace_title:"Rechercher / remplacer",
allreplaced:"Toutes les occurrences de la cha\u00EEne recherch\u00E9e ont \u00E9t\u00E9 remplac\u00E9es.",
findwhat:"Rechercher ceci",
replacewith:"Remplacer par",
direction:"Direction",
up:"Vers le haut",
down:"Vers le bas",
mcase:"Sensible \u00E0 la casse",
findnext:"Rechercher le suivant",
replace:"Remplacer",
replaceall:"Tout remplacer"
});
tinyMCE.addI18n('fr.style_dlg',{
title:"\u00C9diter la feuille de style",
apply:"Appliquer",
text_tab:"Texte",
background_tab:"Fond",
block_tab:"Bloc",
box_tab:"Bo\u00EEte",
border_tab:"Bordure",
list_tab:"Liste",
positioning_tab:"Positionnement",
text_props:"Texte",
text_font:"Police",
text_size:"Taille",
text_weight:"Gras",
text_style:"Style",
text_variant:"Variante",
text_lineheight:"Hauteur de ligne",
text_case:"Casse",
text_color:"Couleur",
text_decoration:"D\u00E9coration",
text_overline:"ligne au-dessus",
text_underline:"soulign\u00E9",
text_striketrough:"barr\u00E9",
text_blink:"clignotant",
text_none:"aucun",
background_color:"Couleur de fond",
background_image:"Image de fond",
background_repeat:"R\u00E9p\u00E9ter",
background_attachment:"Attachement",
background_hpos:"Position horizontale",
background_vpos:"Position verticale",
block_wordspacing:"Espacement des mots ",
block_letterspacing:"Espacement des lettres",
block_vertical_alignment:"Alignement vertical",
block_text_align:"Alignement du texte",
block_text_indent:"Indentation du texte",
block_whitespace:"Fin de ligne",
block_display:"Affichage",
box_width:"Largeur",
box_height:"Hauteur",
box_float:"Flottant",
box_clear:"Vider",
padding:"Espacement",
same:"Identique pour tous",
top:"Haut",
right:"Droit",
bottom:"Bas",
left:"Gauche",
margin:"Marge",
style:"Style",
width:"Largeur",
height:"Hauteur",
color:"Couleur",
list_type:"Type",
bullet_image:"Image de puce",
position:"Position",
positioning_type:"Type",
visibility:"Visibilit\u00E9",
zindex:"Z-index",
overflow:"D\u00E9bordement",
placement:"Placement",
clip:"Clip"
});