tinyMCE.addI18n({nl:{
common:{
edit_confirm:"Weet u zeker dat u tekst in WYSIWYG mode wilt bewerken in dit tekstveld?",
apply:"Toepassen",
insert:"Invoegen",
update:"Bijwerken",
cancel:"Annuleren",
close:"Sluiten",
browse:"Bladeren",
class_name:"Klasse",
not_set:"- Standaard -",
clipboard_msg:"Kopi\u00EBren/knippen/plakken is niet beschikbaar in Mozilla en Firefox.\nWilt u meer informatie over deze beperking?",
clipboard_no_support:"Kopi\u00EBren/knippen/plakken wordt niet ondersteund door uw browser, gebruik hiervoor de sneltoetsen.",
popup_blocked:"U zult uw popup-blocker tijdelijk moeten uitschakelen voor deze website om gebruik te kunnen maken van alle functies van deze teksteditor.",
invalid_data:"Fout: Er zijn ongeldige waardes ingevoerd, deze zijn rood gemarkeerd.",
more_colors:"Meer kleuren"
},
contextmenu:{
align:"Uitlijning",
left:"Links",
center:"Centreren",
right:"Rechts",
full:"Uitvullen"
},
insertdatetime:{
date_fmt:"%d-%m-%Y",
time_fmt:"%H:%M:%S",
insertdate_desc:"Datum invoegen",
inserttime_desc:"Tijd invoegen",
months_long:"Januari,Februari,Maart,April,Mei,Juni,Juli,Augustus,September,Oktober,November,December",
months_short:"Jan,Feb,Mar,Apr,Mei,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
day_long:"Zondag,Maandag,Dinsdag,Woensdag,Donderdag,Vrijdag,Zaterdag,Zondag",
day_short:"zo,ma,di,wo,do,vr,za,zo"
},
print:{
print_desc:"Afdrukken"
},
preview:{
preview_desc:"Voorbeeld"
},
directionality:{
ltr_desc:"Van links naar rechts",
rtl_desc:"Van rechts naar links"
},
layer:{
insertlayer_desc:"Nieuwe laag invoegen",
forward_desc:"Volgende laag",
backward_desc:"Vorige laag",
absolute_desc:"Absoluut positioneren inschakelen",
content:"Nieuwe laag..."
},
save:{
save_desc:"Opslaan",
cancel_desc:"Alle wijzigingen annuleren"
},
nonbreaking:{
nonbreaking_desc:"Open ruimte invoegen"
},
iespell:{
iespell_desc:"Spellingcontrole",
download:"ieSpell niet gevonden. Wilt u deze nu installeren?"
},
advhr:{
advhr_desc:"Scheidingslijn"
},
emotions:{
emotions_desc:"Emoties"
},
searchreplace:{
search_desc:"Zoeken",
replace_desc:"Zoeken/Vervangen"
},
advimage:{
image_desc:"Afbeelding invoegen/bewerken"
},
advlink:{
link_desc:"Link invoegen/bewerken"
},
xhtmlxtras:{
cite_desc:"Citaat",
abbr_desc:"Afkorting",
acronym_desc:"Synoniem",
del_desc:"Verwijderd",
ins_desc:"Ingevoegd",
attribs_desc:"Attributen invoegen/bewerken"
},
style:{
desc:"CSS Stijl bewerken"
},
paste:{
paste_text_desc:"Als platte tekst plakken",
paste_word_desc:"Vanuit Word plakken",
selectall_desc:"Alles selecteren",
plaintext_mode_sticky:"Plakken is nu in plattetekstmodus. Klik nog een keer om terug te gaan naar normaal plakken. Nadat u iets plakt, keert u terug naar normaal plakken.",
plaintext_mode:"Plakken is nu in plattetekstmoduse. Klik nog een keer om terug te gaan naar normaal plakken."
},
paste_dlg:{
text_title:"Gebruik Ctrl+V om tekst in het venster te plakken.",
text_linebreaks:"Regelafbreking bewaren",
word_title:"Gebruik Ctrl+V om tekst in het venster te plakken."
},
table:{
desc:"Nieuwe tabel invoegen",
row_before_desc:"Rij boven invoegen",
row_after_desc:"Rij onder invoegen",
delete_row_desc:"Rij verwijderen",
col_before_desc:"Kolom links invoegen",
col_after_desc:"Kolom rechts invoegen",
delete_col_desc:"Kolom verwijderen",
split_cells_desc:"Cellen splitsen",
merge_cells_desc:"Cellen samenvoegen",
row_desc:"Rij-eigenschappen",
cell_desc:"Cel-eigenschappen",
props_desc:"Tabeleigenschappen",
paste_row_before_desc:"Rij boven plakken",
paste_row_after_desc:"Rij onder plakken",
cut_row_desc:"Rij knippen",
copy_row_desc:"Rij kopi\u00EBren",
del:"Tabel verwijderen",
row:"Rij",
col:"Kolom",
cell:"Cel"
},
autosave:{
unload_msg:"De wijzigingen zullen verloren gaan als u nu deze pagina verlaat.",
restore_content:"Automatisch opgeslagen inhoud laden.",
warning_message:"Als u de opgeslagen inhoud laadt, verliest u de inhoud die zich momenteel in de editor bevindt.\n\nWeet u zeker dat u de opgeslagen inhoud wilt laden?"
},
fullscreen:{
desc:"Volledig scherm"
},
media:{
desc:"Media invoegen/bewerken",
edit:"Media bewerken"
},
fullpage:{
desc:"Documenteigenschappen"
},
template:{
desc:"Voorgedefinieerd sjabloon invoegen"
},
visualchars:{
desc:"Zichtbare symbolen"
},
spellchecker:{
desc:"Spellingcontrole",
menu:"Instellingen spellingcontrole",
ignore_word:"Woord negeren",
ignore_words:"Alles negeren",
langs:"Talen",
wait:"Een ogenblik geduld\u2026",
sug:"Suggesties",
no_sug:"Geen suggesties",
no_mpell:"Geen spelfouten gevonden."
},
pagebreak:{
desc:"Pagina-einde invoegen"
},
advlist:{
types:"Types",
def:"Standaard",
lower_alpha:"Alfa (klein)",
lower_greek:"Griekse letters (klein)",
lower_roman:"Romeinse letters (klein)",
upper_alpha:"Alfa (groot)",
upper_roman:"Romeinse letters (groot)",
circle:"Cirkel",
disc:"Schijf",
square:"Vierkant"
}}});
tinyMCE.addI18n('nl.advanced',{
style_select:"Stijlen",
font_size:"Tekengrootte",
fontdefault:"Lettertype",
block:"Opmaak",
paragraph:"Alinea",
div:"Div",
address:"Adres",
pre:"Vaste opmaak",
h1:"Kop 1",
h2:"Kop 2",
h3:"Kop 3",
h4:"Kop 4",
h5:"Kop 5",
h6:"Kop 6",
blockquote:"Citaat",
code:"Code",
samp:"Codevoorbeeld",
dt:"Definitieterm",
dd:"Definitiebeschrijving",
bold_desc:"Vet (Ctrl+B)",
italic_desc:"Cursief (Ctrl+I)",
underline_desc:"Onderstrepen (Ctrl+U)",
striketrough_desc:"Doorhalen",
justifyleft_desc:"Links uitlijnen",
justifycenter_desc:"Centreren",
justifyright_desc:"Rechts uitlijnen",
justifyfull_desc:"Uitvullen",
bullist_desc:"Opsommingstekens",
numlist_desc:"Nummering",
outdent_desc:"Inspringing verkleinen",
indent_desc:"Inspringing vergroten",
undo_desc:"Ongedaan maken (Ctrl+Z)",
redo_desc:"Herhalen (Ctrl+Y)",
link_desc:"Link invoegen/bewerken",
unlink_desc:"Link verwijderen",
image_desc:"Afbeelding invoegen/bewerken",
cleanup_desc:"Code opruimen",
code_desc:"HTML bron bewerken",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Scheidingslijn invoegen",
removeformat_desc:"Opmaak verwijderen",
custom1_desc:"Uw eigen beschrijving hier",
forecolor_desc:"Tekstkleur",
backcolor_desc:"Tekstmarkeringskleur",
charmap_desc:"Symbool invoegen",
visualaid_desc:"Hulplijnen weergeven",
anchor_desc:"Anker invoegen/bewerken",
cut_desc:"Knippen",
copy_desc:"Kopi\u00EBren",
paste_desc:"Plakken",
image_props_desc:"Afbeeldingseigenschappen",
newdocument_desc:"Nieuw document",
help_desc:"Help",
blockquote_desc:"Citaat",
clipboard_msg:"Kopi\u00EBren/knippen/plakken is niet beschikbaar in Mozilla en Firefox.\nWilt u meer informatie over deze beperking?",
path:"Pad",
newdocument:"Weet u zeker dat u alle inhoud wilt wissen?",
toolbar_focus:"Spring naar werkbalk - Alt+Q, Spring naar tekst - Alt-Z, Spring naar elementpad - Alt-X",
more_colors:"Meer kleuren"
});
tinyMCE.addI18n('nl.advanced_dlg',{
about_title:"Over TinyMCE",
about_general:"Info",
about_help:"Help",
about_license:"Licentie",
about_plugins:"Invoegtoepassingen",
about_plugin:"Invoegtoepassing",
about_author:"Auteur",
about_version:"Versie",
about_loaded:"Geladen Invoegtoepassingen",
anchor_title:"Anker invoegen/bewerken",
anchor_name:"Ankernaam",
code_title:"HTML Bron",
code_wordwrap:"Automatische terugloop",
colorpicker_title:"Kleuren",
colorpicker_picker_tab:"Alle kleuren",
colorpicker_picker_title:"Alle kleuren",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Paletkleuren",
colorpicker_named_tab:"Benoemd",
colorpicker_named_title:"Benoemde kleuren",
colorpicker_color:"Kleur:",
colorpicker_name:"Naam:",
charmap_title:"Symbolen",
image_title:"Afbeelding invoegen/bewerken",
image_src:"Bestand/URL",
image_alt:"Beschrijving",
image_list:"Lijst",
image_border:"Rand",
image_dimensions:"Afmetingen",
image_vspace:"Verticale ruimte",
image_hspace:"Horizontale ruimte",
image_align:"Uitlijning",
image_align_baseline:"Basislijn",
image_align_top:"Boven",
image_align_middle:"Midden",
image_align_bottom:"Onder",
image_align_texttop:"Bovenkant tekst",
image_align_textbottom:"Onderkant tekst",
image_align_left:"Links",
image_align_right:"Rechts",
link_title:"Link invoegen/bewerken",
link_url:"URL",
link_target:"Doel",
link_target_same:"Link in hetzelfde venster openen",
link_target_blank:"Link in een nieuw venster openen",
link_titlefield:"Titel",
link_is_email:"De ingevoerde URL lijkt op een e-mailadres. Wilt u de vereiste mailto: tekst voorvoegen?",
link_is_external:"De ingevoerde URL lijkt op een externe link. Wilt u de vereiste http:// tekst voorvoegen?",
link_list:"Link lijst"
});
tinyMCE.addI18n('nl.advimage_dlg',{
tab_general:"Algemeen",
tab_appearance:"Weergave",
tab_advanced:"Geavanceerd",
general:"Algemeen",
title:"Titel",
preview:"Voorbeeld",
constrain_proportions:"Verhouding behouden",
langdir:"Taalrichting",
langcode:"Taalcode",
long_desc:"Uitgebreide beschrijving",
style:"Stijl",
classes:"Klasses",
ltr:"Van links naar rechts",
rtl:"Van rechts naar links",
id:"Id",
map:"Afbeeldingsplattegrond",
swap_image:"Afbeelding wisselen",
alt_image:"Alternatieve afbeeldingen",
mouseover:"Bij muis over",
mouseout:"Bij muis uit",
misc:"Diversen",
example_img:"Voorbeeldweergave",
missing_alt:"Wilt u de afbeelding zonder beschrijving invoegen? De afbeelding wordt dan mogelijk niet opgemerkt door mensen met een visuele handicap, of welke zonder afbeeldingen browsen.",
dialog_title:"Afbeelding invoegen/bewerken",
src:"Bestand/URL",
alt:"Beschrijving",
list:"Lijst",
border:"Rand",
dimensions:"Afmetingen",
vspace:"Verticale ruimte",
hspace:"Horizontale ruimte",
align:"Uitlijning",
align_baseline:"Basislijn",
align_top:"Boven",
align_middle:"Midden",
align_bottom:"Onder",
align_texttop:"Bovenkant tekst",
align_textbottom:"Onderkant tekst",
align_left:"Links",
align_right:"Rechts",
image_list:"Lijst"
});
tinyMCE.addI18n('nl.advlink_dlg',{
title:"Link invoegen/bewerken",
url:"URL",
target:"Doel",
titlefield:"Titel",
is_email:"De ingevoerde URL lijkt op een e-mailadres. Wilt u de vereiste mailto: tekst voorvoegen?",
is_external:"De ingevoerde URL lijkt op een externe link. Wilt u de vereiste http:// tekst voorvoegen?",
list:"Lijst",
general_tab:"Algemeen",
popup_tab:"Popup",
events_tab:"Gebeurtenissen",
advanced_tab:"Geavanceerd",
general_props:"Algemene eigenschappen",
popup_props:"Popup eigenschappen",
event_props:"Gebeurtenissen",
advanced_props:"Geavanceerde eigenschappen",
popup_opts:"Opties",
anchor_names:"Ankers",
target_same:"In dit venster / frame openen",
target_parent:"In bovenliggend venster / frame openen",
target_top:"In bovenste frame openen (vervangt gehele pagina)",
target_blank:"In nieuw venster openen",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Venstertitel",
popup_return:"'return false' invoegen",
popup_scrollbars:"Scrollbalken weergeven",
popup_statusbar:"Statusbalk weergeven",
popup_toolbar:"Werkbalk weergeven",
popup_menubar:"Menubalk weergeven",
popup_location:"Lokatiebalk weergeven",
popup_resizable:"Aanpasbaar venster",
popup_dependent:"Afhankelijk (Alleen Mozilla/Firefox)",
popup_size:"Grootte",
popup_position:"Positie (X/Y)",
id:"Id",
style:"Stijl",
classes:"Klassen",
target_name:"Doel",
langdir:"Taalrichting",
target_langcode:"Taal",
langcode:"Taalcode",
encoding:"Taalcodering",
mime:"MIME type",
rel:"Relatie van pagina tot doel",
rev:"Relatie van doel tot pagina",
tabindex:"Tabvolgorde",
accesskey:"Toegangstoets",
ltr:"Van links naar rechts",
rtl:"Van rechts naar links",
link_list:"Lijst"
});
tinyMCE.addI18n('nl.emotions_dlg',{
title:"Emotie invoegen",
desc:"Emoties",
cool:"Stoer",
cry:"Huilen",
embarassed:"Schamen",
foot_in_mouth:"Verstomd",
frown:"Wenkbrauw ophalen",
innocent:"Onschuldig",
kiss:"Zoenen",
laughing:"Lachen",
money_mouth:"Hebberig",
sealed:"Afgesloten",
smile:"Lachen",
surprised:"Verrast",
tongue_out:"Tong uitsteken",
undecided:"Onbeslist",
wink:"Knipogen",
yell:"Roepen"
});
tinyMCE.addI18n('nl.media_dlg',{
title:"Media invoegen/bewerken",
general:"Algemeen",
advanced:"Geavanceerd",
file:"Bestand/URL",
list:"Lijst",
size:"Afmetingen",
preview:"Voorbeeld",
constrain_proportions:"Verhouding bewaren",
type:"Type",
id:"Id",
name:"Naam",
class_name:"Klasse",
vspace:"V-Ruimte",
hspace:"H-Ruimte",
play:"Automatisch afspelen",
loop:"Herhalen",
menu:"Menu Weergeven",
quality:"Kwaliteit",
scale:"Schaal",
align:"Uitlijning",
salign:"Schaaluitlijning",
wmode:"WMode",
bgcolor:"Achtergrond",
base:"Basis",
flashvars:"Variabelen",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Verborgen",
controller:"Controller",
kioskmode:"Kioskmodus",
playeveryframe:"Elk frame afspelen",
targetcache:"Doelcache",
correction:"Geen correctie",
enablejavascript:"JavaScript Inschakelen",
starttime:"Starttijd",
endtime:"Eindtijd",
href:"HREF",
qtsrcchokespeed:"Chokesnelheid",
target:"Doel",
volume:"Volume",
autostart:"Automatisch afspelen",
enabled:"Ingeschakeld",
fullscreen:"Volledig scherm",
invokeurls:"URLs laden",
mute:"Geluid dempen",
stretchtofit:"Passend maken",
windowlessvideo:"Video zonder venster",
balance:"Balans",
baseurl:"BasisURL",
captioningid:"Ondertiteling id",
currentmarker:"Huidige markering",
currentposition:"Huidige positie",
defaultframe:"Standaard frame",
playcount:"Afspeelteller",
rate:"Snelheid",
uimode:"UI Modus",
flash_options:"Flash opties",
qt_options:"Quicktime opties",
wmp_options:"Windows mediaspeler opties",
rmp_options:"Real mediaspeler opties",
shockwave_options:"Shockwave opties",
autogotourl:"Automatisch naar URL",
center:"Centreren",
imagestatus:"Afbeeldingstatus",
maintainaspect:"Verhouding bewaren",
nojava:"Geen java",
prefetch:"Voorladen",
shuffle:"Willekeurige volgorde",
console:"Console",
numloop:"Aantal herhalingen",
controls:"Bediening",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Schaal",
swstretchhalign:"H-Schaal",
swstretchvalign:"V-Schaal",
sound:"Geluid",
progress:"Voortgang",
qtsrc:"Quicktime bron",
qt_stream_warn:"Gestreamde RTSP bronnen dienen op het tabblad geavanceerd bij Quicktime bron te worden opgegeven.\nDe niet-gestreamde versie kan dan bij het tabblad algemeen worden opgegeven.",
align_top:"Boven",
align_right:"Rechts",
align_bottom:"Onder",
align_left:"Links",
align_center:"Centreren",
align_top_left:"Linksboven",
align_top_right:"Rechtsboven",
align_bottom_left:"Linksonder",
align_bottom_right:"Rechtsonder",
flv_options:"Flash video-opties",
flv_scalemode:"Schaalmodus",
flv_buffer:"Buffer",
flv_startimage:"Startafbeelding",
flv_starttime:"Starttijd",
flv_defaultvolume:"Standaard volume",
flv_hiddengui:"GUI verbergen",
flv_autostart:"Automatisch afspelen",
flv_loop:"Herhalen",
flv_showscalemodes:"Schaalmodus weergeven",
flv_smoothvideo:"Soepele video",
flv_jscallback:"JS Callback"
});
tinyMCE.addI18n('nl.paste_dlg',{
text_title:"Gebruik Ctrl+V om tekst in het venster te plakken.",
text_linebreaks:"Regelafbreking bewaren",
word_title:"Gebruik Ctrl+V om tekst in het venster te plakken."
});
tinyMCE.addI18n('nl.searchreplace_dlg',{
searchnext_desc:"Opnieuw zoeken",
notfound:"Het doorzoeken is voltooid. De zoekterm kon niet meer worden gevonden.",
search_title:"Zoeken",
replace_title:"Zoeken/Vervangen",
allreplaced:"Alle instanties van de zoekterm zijn vervangen.",
findwhat:"Zoeken naar",
replacewith:"Vervangen door",
direction:"Richting",
up:"Omhoog",
down:"Omlaag",
mcase:"Identieke hoofdletters/kleine letters",
findnext:"Zoeken",
replace:"Vervangen",
replaceall:"Alles verv."
});
tinyMCE.addI18n('nl.style_dlg',{
title:"CSS Stijl bewerken",
apply:"Toepassen",
text_tab:"Tekst",
background_tab:"Achtergrond",
block_tab:"Blok",
box_tab:"Box",
border_tab:"Rand",
list_tab:"Lijst",
positioning_tab:"Positionering",
text_props:"Tekst",
text_font:"Lettertype",
text_size:"Tekengrootte",
text_weight:"Gewicht",
text_style:"Stijl",
text_variant:"Variant",
text_lineheight:"Lijnhoogte",
text_case:"Hoofdlettergebruik",
text_color:"Kleur",
text_decoration:"Decoratie",
text_overline:"Overhalen",
text_underline:"Onderstrepen",
text_striketrough:"Doorhalen",
text_blink:"Knipperen",
text_none:"Niets",
background_color:"Achtergrondkleur",
background_image:"Achtergrondafbeelding",
background_repeat:"Herhalen",
background_attachment:"Bijlage",
background_hpos:"Horizontale positie",
background_vpos:"Verticale positie",
block_wordspacing:"Woordruimte",
block_letterspacing:"Letterruimte",
block_vertical_alignment:"Verticale uitlijning",
block_text_align:"Tekstuitlijning",
block_text_indent:"Inspringen",
block_whitespace:"Witruimte",
block_display:"Weergave",
box_width:"Breedte",
box_height:"Hoogte",
box_float:"Zweven",
box_clear:"Vrijhouden",
padding:"Opening",
same:"Alles hetzelfde",
top:"Boven",
right:"Rechts",
bottom:"Onder",
left:"Links",
margin:"Marge",
style:"Stijl",
width:"Breedte",
height:"Hoogte",
color:"Kleur",
list_type:"Type",
bullet_image:"Opsommingsteken",
position:"Positie",
positioning_type:"Type",
visibility:"Zichtbaarheid",
zindex:"Z-index",
overflow:"Overvloeien",
placement:"Plaatsing",
clip:"Clip"
});