tinyMCE.addI18n({pt:{
common:{
edit_confirm:"Deseja usar o modo de edi\u00E7\u00E3o avan\u00E7ado neste campo de texto?",
apply:"Aplicar",
insert:"Inserir",
update:"Atualizar",
cancel:"Cancelar",
close:"Fechar",
browse:"Procurar",
class_name:"Classe",
not_set:"-- N/A --",
clipboard_msg:"Copiar/recortar/colar n\u00E3o est\u00E1 dispon\u00EDvel no Mozilla e Firefox.\nDeseja mais informa\u00E7\u00F5es sobre este problema?",
clipboard_no_support:"O seu browser n\u00E3o suporta esta fun\u00E7\u00E3o, use os atalhos do teclado.",
popup_blocked:"Detectamos que o seu bloqueador de popups bloqueou uma janela que \u00E9 essencial para a aplica\u00E7\u00E3o. Voc\u00EA precisa desativar o bloqueador de janelas de popups para utilizar esta ferramenta.",
invalid_data:"Erro: Valores inv\u00E1lidos marcados em vermelho.",
more_colors:"Mais Cores"
},
contextmenu:{
align:"Alinhamento",
left:"Esquerda",
center:"Centro",
right:"Direita",
full:"Justificado"
},
insertdatetime:{
date_fmt:"%d-%m-%Y",
time_fmt:"%H:%M:%S",
insertdate_desc:"Inserir data",
inserttime_desc:"Inserir hora",
months_long:"Janeiro,Fevereiro,Mar\u00E7o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro",
months_short:"Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez",
day_long:"Domingo,Segunda-feira,Ter\u00E7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00E1bado,Domingo",
day_short:"Dom,Seg,Ter,Qua,Qui,Sex,Sab,Dom"
},
print:{
print_desc:"Imprimir"
},
preview:{
preview_desc:"Pr\u00E9-visualizar"
},
directionality:{
ltr_desc:"Da esquerda para direita",
rtl_desc:"Da direita para esquerda"
},
layer:{
insertlayer_desc:"Inserir nova camada",
forward_desc:"Mover para frente",
backward_desc:"Mover para tr\u00E1s",
absolute_desc:"Alternar o posicionamento absoluto",
content:"Nova camada..."
},
save:{
save_desc:"Salvar",
cancel_desc:"Cancelar todas as altera\u00E7\u00F5es"
},
nonbreaking:{
nonbreaking_desc:"Inserir um espa\u00E7o \"sem quebra\""
},
iespell:{
iespell_desc:"Verificar ortografia",
download:"Plugin de ortografia n\u00E3o-detectado. Deseja instalar agora?"
},
advhr:{
advhr_desc:"Separador horizontal"
},
emotions:{
emotions_desc:"Emoticons"
},
searchreplace:{
search_desc:"Localizar",
replace_desc:"Localizar/substituir"
},
advimage:{
image_desc:"Inserir/editar imagem"
},
advlink:{
link_desc:"Inserir/editar hyperlink"
},
xhtmlxtras:{
cite_desc:"Cita\u00E7\u00E3o",
abbr_desc:"Abrevia\u00E7\u00E3o",
acronym_desc:"Acr\u00F4nimo",
del_desc:"Apagar",
ins_desc:"Inserir",
attribs_desc:"Inserir/Editar atributos"
},
style:{
desc:"Editar CSS"
},
paste:{
paste_text_desc:"Colar como texto simples",
paste_word_desc:"Colar (copiado do WORD)",
selectall_desc:"Selecionar tudo",
plaintext_mode_sticky:"Paste is now in plain text mode. Click again to toggle back to regular paste mode. After you paste something you will be returned to regular paste mode.",
plaintext_mode:"Paste is now in plain text mode. Click again to toggle back to regular paste mode."
},
paste_dlg:{
text_title:"Use CTRL+V para colar o texto na janela.",
text_linebreaks:"Manter quebras de linha",
word_title:"Use CTRL+V para colar o texto na janela."
},
table:{
desc:"Inserir nova tabela",
row_before_desc:"Inserir linha antes",
row_after_desc:"Inserir linha depois",
delete_row_desc:"Apagar linha",
col_before_desc:"Inserir coluna antes",
col_after_desc:"Inserir coluna depois",
delete_col_desc:"Remover coluna",
split_cells_desc:"Dividir c\u00E9lulas",
merge_cells_desc:"Unir c\u00E9lulas",
row_desc:"Propriedades das linhas",
cell_desc:"Propriedades das c\u00E9lulas",
props_desc:"Propriedades da tabela",
paste_row_before_desc:"Colar linha antes",
paste_row_after_desc:"Colar linha depois",
cut_row_desc:"Recortar linha",
copy_row_desc:"Copiar linha",
del:"Apagar tabela",
row:"Linha",
col:"Coluna",
cell:"C\u00E9lula"
},
autosave:{
unload_msg:"As mudan\u00E7as efetuadas ser\u00E3o perdidas se sair desta p\u00E1gina.",
restore_content:"Restore auto-saved content.",
warning_message:"If you restore the saved content, you will lose all the content that is currently in the editor.\n\nAre you sure you want to restore the saved content?."
},
fullscreen:{
desc:"Tela Inteira"
},
media:{
desc:"Inserir/Editar m\u00EDdia incorporada",
edit:"Editar m\u00EDdia incorporada"
},
fullpage:{
desc:"Propriedades do Documento"
},
template:{
desc:"Inserir template"
},
visualchars:{
desc:"Caracteres de controle visual ligado/desligado"
},
spellchecker:{
desc:"Alternar verifica\u00E7\u00E3o ortogr\u00E1fica",
menu:"Configura\u00E7\u00F5es de ortografia",
ignore_word:"Ignorar palavra",
ignore_words:"Ignorar tudo",
langs:"Linguagens",
wait:"Aguarde...",
sug:"Sugest\u00F5es",
no_sug:"Sem sugest\u00F5es",
no_mpell:"N\u00E3o foram detectados erros de ortografia."
},
pagebreak:{
desc:"Inserir quebra de p\u00E1gina."
},
advlist:{
types:"Types",
def:"Default",
lower_alpha:"Lower alpha",
lower_greek:"Lower greek",
lower_roman:"Lower roman",
upper_alpha:"Upper alpha",
upper_roman:"Upper roman",
circle:"Circle",
disc:"Disc",
square:"Square"
}}});
tinyMCE.addI18n('pt.advanced',{
style_select:"Estilos",
font_size:"Tamanho",
fontdefault:"Tipo de fonte",
block:"Formata\u00E7\u00E3o",
paragraph:"Par\u00E1grafo",
div:"Div",
address:"Endere\u00E7o",
pre:"Pr\u00E9-formatado",
h1:"T\u00EDtulo 1",
h2:"T\u00EDtulo 2",
h3:"T\u00EDtulo 3",
h4:"T\u00EDtulo 4",
h5:"T\u00EDtulo 5",
h6:"T\u00EDtulo 6",
blockquote:"Cita\u00E7\u00E3o em bloco",
code:"C\u00F3digo",
samp:"Amostra de c\u00F3digo",
dt:"Termo da defini\u00E7\u00E3o",
dd:"Descri\u00E7\u00E3o da defini\u00E7\u00E3o",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"It\u00E1lico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Riscado",
justifyleft_desc:"Alinhar \u00E0 esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar \u00E0 direita",
justifyfull_desc:"Justificar",
bullist_desc:"Marcadores",
numlist_desc:"Numera\u00E7\u00E3o",
outdent_desc:"Diminuir recuo",
indent_desc:"Aumentar recuo",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar hyperlink",
unlink_desc:"Remover hyperlink",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar c\u00F3digo incorreto",
code_desc:"Editar c\u00F3digo fonte",
sub_desc:"Inferior \u00E0 linha",
sup_desc:"Superior \u00E0 linha",
hr_desc:"Inserir separador horizontal",
removeformat_desc:"Remover formata\u00E7\u00E3o",
custom1_desc:"Insira aqui a sua descri\u00E7\u00E3o personalizada",
forecolor_desc:"Selecionar a cor do texto",
backcolor_desc:"Selecionar a cor de fundo",
charmap_desc:"Inserir caracteres especiais",
visualaid_desc:"Alternar guias/elementos invis\u00EDveis",
anchor_desc:"Inserir/editar \u00E2ncora",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Cita\u00E7\u00E3o em bloco",
clipboard_msg:"Copiar/recortar/colar n\u00E3o est\u00E1 dispon\u00EDvel no Mozilla e Firefox. Deseja mais informa\u00E7\u00F5es sobre este problema?",
path:"Endere\u00E7o",
newdocument:"Tem a certeza que deseja apagar tudo?",
toolbar_focus:"Ir para as ferramentas - Alt+Q, Ir para o editor - Alt-Z, Ir para o endere\u00E7o do elemento - Alt-X",
more_colors:"Mais cores"
});
tinyMCE.addI18n('pt.advanced_dlg',{
about_title:"Sobre o TinyMCE",
about_general:"Sobre",
about_help:"Ajuda",
about_license:"Licen\u00E7a",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Vers\u00E3o",
about_loaded:"Plugins Instalados",
anchor_title:"Inserir/editar \u00E2ncora",
anchor_name:"Nome da \u00E2ncora",
code_title:"Editor HTML",
code_wordwrap:"Quebra autom\u00E1tica de linha",
colorpicker_title:"Selecione uma cor",
colorpicker_picker_tab:"Editor",
colorpicker_picker_title:"Editor de Cores",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta de Cores",
colorpicker_named_tab:"Personalizadas",
colorpicker_named_title:"Cores Personalizadas",
colorpicker_color:"Cor:",
colorpicker_name:"Nome:",
charmap_title:"Selecionar caracteres personalizados",
image_title:"Inserir/editar imagem",
image_src:"Endere\u00E7o da imagem",
image_alt:"Descri\u00E7\u00E3o da imagem",
image_list:"Lista de imagens",
image_border:"Limites",
image_dimensions:"Dimens\u00F5es",
image_vspace:"Espa\u00E7o Vertical",
image_hspace:"Espa\u00E7o Horizontal",
image_align:"Alinhamento",
image_align_baseline:"Sobre a linha de texto",
image_align_top:"Topo",
image_align_middle:"Meio",
image_align_bottom:"Abaixo",
image_align_texttop:"Topo do texto",
image_align_textbottom:"Base do texto",
image_align_left:"Esquerda",
image_align_right:"Direita",
link_title:"Inserir/editar hyperlink",
link_url:"URL do hyperink",
link_target:"Alvo",
link_target_same:"Abrir hyperlink na mesma janela",
link_target_blank:"Abrir hyperlink em nova janela",
link_titlefield:"T\u00EDtulo",
link_is_email:"A URL digitada parece ser um endere\u00E7o de e-mail. Deseja acrescentar o prefixo necess\u00E1rio mailto:?",
link_is_external:"A URL digitada parece conduzir a um link externo. Deseja acrescentar o prefixo necess\u00E1rio http://?",
link_list:"Lista de Links"
});
tinyMCE.addI18n('pt.advimage_dlg',{
tab_general:"Geral",
tab_appearance:"Apar\u00EAncia",
tab_advanced:"Avan\u00E7ado",
general:"Geral",
title:"T\u00EDtulo",
preview:"Pr\u00E9-Visualiza\u00E7\u00E3o",
constrain_proportions:"Manter propor\u00E7\u00F5es",
langdir:"Dire\u00E7\u00E3o do texto",
langcode:"C\u00F3digo do idioma",
long_desc:"Descri\u00E7\u00E3o extensa",
style:"Estilo",
classes:"Classes",
ltr:"Da esquerda para a direita",
rtl:"Da direita para a esquerda",
id:"Id",
map:"Mapa de imagem",
swap_image:"Trocar imagem",
alt_image:"Imagem alternativa",
mouseover:"mouseover",
mouseout:"mouseout",
misc:"Misto",
example_img:"Pr\u00E9-Visualiza\u00E7\u00E3o",
missing_alt:"Tem certeza que deseja continuar sem acrescentar uma descri\u00E7\u00E3o \u00E0 imagem? (Isto pode gerar problemas de acessibilidade em alguns navegadores)",
dialog_title:"Inserir/editar imagem",
src:"Endere\u00E7o da imagem",
alt:"Descri\u00E7\u00E3o da imagem",
list:"Lista de imagens",
border:"Limite",
dimensions:"Dimens\u00F5es",
vspace:"Espa\u00E7o vertical",
hspace:"Espa\u00E7o horizontal",
align:"Alinhamento",
align_baseline:"Sobre a linha de texto",
align_top:"Topo",
align_middle:"Meio",
align_bottom:"Abaixo",
align_texttop:"Topo do texto",
align_textbottom:"Base do texto",
align_left:"Esquerda",
align_right:"Direita",
image_list:"Lista de imagens"
});
tinyMCE.addI18n('pt.advlink_dlg',{
title:"Inserir/editar hyperlink",
url:"URL do hyperlink",
target:"Alvo",
titlefield:"T\u00EDtulo",
is_email:"A URL digitada parece ser um endere\u00E7o de e-mail. Deseja acrescentar o prefixo necess\u00E1rio mailto:?",
is_external:"A URL digitada parece conduzir a um link externo. Deseja acrescentar o prefixo necess\u00E1rio http://?",
list:"Lista de hyperlinks",
general_tab:"Geral",
popup_tab:"Popup",
events_tab:"Eventos",
advanced_tab:"Avan\u00E7ado",
general_props:"Propriedades gerais",
popup_props:"Propriedades de popup",
event_props:"Eventos",
advanced_props:"Propriedades avan\u00E7adas",
popup_opts:"Op\u00E7\u00F5es",
anchor_names:"\u00C2ncoras",
target_same:"Abrir nesta janela/quadro",
target_parent:"Abrir na janela/quadro pai",
target_top:"Abrir na p\u00E1gina inteira (substitui todos os quadros)",
target_blank:"Abrir numa nova janela",
popup:"Popup javascript",
popup_url:"URL do popup",
popup_name:"Nome da janela",
popup_return:"Inserir \"return false\"",
popup_scrollbars:"Mostrar as barras de scroll",
popup_statusbar:"Mostrar a barra de status",
popup_toolbar:"Mostrar a barra de ferramentas",
popup_menubar:"Mostrar a barra de menu",
popup_location:"Mostrar a barra de endere\u00E7os",
popup_resizable:"Permitir altera\u00E7\u00E3o do tamanho da janela",
popup_dependent:"Dependente (Mozilla/Firefox apenas)",
popup_size:"Tamanho",
popup_position:"Posi\u00E7\u00E3o (X/Y)",
id:"Id",
style:"Estilo",
classes:"Classes",
target_name:"Nome do alvo",
langdir:"Dire\u00E7\u00E3o do texto",
target_langcode:"Idioma alvo",
langcode:"C\u00F3digo do idioma",
encoding:"Codifica\u00E7\u00E3o de caracteres",
mime:"Tipo MIME alvo",
rel:"Rela\u00E7\u00E3o p\u00E1gina/alvo",
rev:"Rela\u00E7\u00E3o alvo/p\u00E1gina",
tabindex:"Tabindex",
accesskey:"Chave de acesso",
ltr:"Da esquerda para a direita",
rtl:"Da direita para a esquerda",
link_list:"Lista de hyperlinks"
});
tinyMCE.addI18n('pt.emotions_dlg',{
title:"Inserir emoticon",
desc:"Emoticons",
cool:"Fixe",
cry:"Chor\u00E3o",
embarassed:"Embara\u00E7ado",
foot_in_mouth:"Disse asneira",
frown:"Decep\u00E7\u00E3o",
innocent:"Inocente",
kiss:"Beijo",
laughing:"Riso",
money_mouth:"Avarez",
sealed:"Boca Fechada",
smile:"Sorriso",
surprised:"Surpresa",
tongue_out:"L\u00EDngua de fora",
undecided:"Indeciso",
wink:"Piscadela",
yell:"Irado"
});
tinyMCE.addI18n('pt.media_dlg',{
title:"Inserir/Editar m\u00EDdia incorporada",
general:"Geral",
advanced:"Avan\u00E7ado",
file:"Arquivo/URL",
list:"Lista",
size:"Dimens\u00F5es",
preview:"Previs\u00E3o",
constrain_proportions:"Manter propor\u00E7\u00F5es",
type:"Tipo",
id:"Id",
name:"Nome",
class_name:"Classe",
vspace:"Espa\u00E7o vertical",
hspace:"Espa\u00E7o horizontal",
play:"Execu\u00E7\u00E3o autom\u00E1tica",
loop:"Repeti\u00E7\u00E3o autom\u00E1tica",
menu:"Mostrar menu",
quality:"Qualidade",
scale:"Escala",
align:"Alinhamento",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fundo",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Oculto",
controller:"Controlador",
kioskmode:"Modo Quiosque",
playeveryframe:"Executar todas as frames",
targetcache:"Cache alvo",
correction:"Sem correc\u00E7\u00F5es",
enablejavascript:"Disponibilizar javaScript",
starttime:"Hora de in\u00EDcio",
endtime:"Hora do fim",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Alvo",
volume:"Volume",
autostart:"Execu\u00E7\u00E3o autom\u00E1tica",
enabled:"Ativado",
fullscreen:"Tela inteira",
invokeurls:"Invocar URLs",
mute:"Mudo",
stretchtofit:"Estender",
windowlessvideo:"V\u00EDdeo sem janela",
balance:"Stereo",
baseurl:"Base URL",
captioningid:"Id de legenda",
currentmarker:"Marcador atual",
currentposition:"Posi\u00E7\u00E3o atual",
defaultframe:"Frame padr\u00E3o",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Op\u00E7\u00F5es Flash",
qt_options:"Op\u00E7\u00F5es Quicktime",
wmp_options:"Op\u00E7\u00F5es Windows Media Player",
rmp_options:"Op\u00E7\u00F5es Real Media Player",
shockwave_options:"Op\u00E7\u00F5es Shockwave",
autogotourl:"Auto goto URL",
center:"Centro",
imagestatus:"Status da imagem",
maintainaspect:"Manter aspecto",
nojava:"no java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Controles",
scriptcallbacks:"callbacks de script",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Som",
progress:"Progresso",
qtsrc:"QT Src",
qt_stream_warn:"Fluxos de recursos rtsp devem ser acrescentados ao campo QT Src no Modo Avan\u00E7ado.\Numa vers\u00E3o sem fluxo tamb\u00E9m deve ser acrescentada ao campo Src.",
align_top:"Topo",
align_right:"Direita",
align_bottom:"Abaixo",
align_left:"Esquerda",
align_center:"Centro",
align_top_left:"Topo esquerda",
align_top_right:"Topo direita",
align_bottom_left:"Abaixo esquerda",
align_bottom_right:"Abaixo direita",
flv_options:"Op\u00E7\u00F5es de Flash video",
flv_scalemode:"Modo escala",
flv_buffer:"Buffer",
flv_startimage:"Imagem inicial",
flv_starttime:"Hora inicial",
flv_defaultvolume:"Volume padr\u00E3o",
flv_hiddengui:"GUI oculta",
flv_autostart:"Execu\u00E7\u00E3o Autom\u00E1tica",
flv_loop:"Loop",
flv_showscalemodes:"Mostrar modos escala",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS callback"
});
tinyMCE.addI18n('pt.paste_dlg',{
text_title:"Use CTRL+V para colar o texto na janela.",
text_linebreaks:"Manter quebras de linha",
word_title:"Use CTRL+V para colar o texto na janela."
});
tinyMCE.addI18n('pt.searchreplace_dlg',{
searchnext_desc:"Localizar novamente",
notfound:"A pesquisa foi conclu\u00EDda sem resultados.",
search_title:"Localizar",
replace_title:"Localizar/substituir",
allreplaced:"Todas as substitui\u00E7\u00F5es foram efetuadas.",
findwhat:"Localizar",
replacewith:"Substituir com",
direction:"Dire\u00E7\u00E3o",
up:"Acima",
down:"Abaixo",
mcase:"Diferenciar mai\u00FAsculas",
findnext:"Localizar pr\u00F3ximo",
replace:"Substituir",
replaceall:"Substituir todos"
});
tinyMCE.addI18n('pt.style_dlg',{
title:"Editar CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fundo",
block_tab:"Bloco",
box_tab:"Caixa",
border_tab:"Limites",
list_tab:"Lista",
positioning_tab:"Posicionamento",
text_props:"Texto",
text_font:"Fonte",
text_size:"Tamanho",
text_weight:"Peso",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Altura da linha",
text_case:"Mai\u00FAscula",
text_color:"Cor",
text_decoration:"Decora\u00E7\u00E3o",
text_overline:"Sobrelinha",
text_underline:"Sublinhado",
text_striketrough:"Riscado",
text_blink:"Piscar",
text_none:"nenhum",
background_color:"Cor de fundo",
background_image:"Imagem de fundo",
background_repeat:"Repetir",
background_attachment:"Fixar",
background_hpos:"Posi\u00E7\u00E3o horizontal",
background_vpos:"Posi\u00E7\u00E3o vertical",
block_wordspacing:"Espa\u00E7amento de palavras",
block_letterspacing:"Espa\u00E7amento de letras",
block_vertical_alignment:"Alinhamento vertical",
block_text_align:"Alinhamento de texto",
block_text_indent:"Indent",
block_whitespace:"Espa\u00E7o",
block_display:"Display",
box_width:"Largura",
box_height:"Altura",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"O mesmo para todos",
top:"Topo",
right:"Direita",
bottom:"Abaixo",
left:"Esquerda",
margin:"Margem",
style:"Estilo",
width:"Largura",
height:"Altura",
color:"Cor",
list_type:"Tipo",
bullet_image:"Imagem de lista",
position:"Posi\u00E7\u00E3o",
positioning_type:"Tipo",
visibility:"Visibilidade",
zindex:"Z-index",
overflow:"Overflow",
placement:"Posicionamento",
clip:"Clip"
});